export const DEFAULT_DRILL_PACKS = [
  {
    id: 'breaststroke-kick-timing',
    title: 'Breaststroke Kick Timing',
    stroke: 'Breaststroke',
    phases: ['Kick Recovery', 'Kick Drive', 'Timing'],
    faults: ['Kick starts too early', 'Late foot snap', 'No glide after kick'],
    objective: 'Build the sequence from heel recovery to foot turn, snap, and short glide so the kick supports forward momentum.',
    primaryCue: 'Heels first, turn late, snap together.',
    cueTheme: 'Patient heel recovery before a fast snap.',
    bestFor: 'Swimmers who rush the kick or lose rhythm between pull, kick, and glide.',
    equipment: 'Wall, board, or fins optional',
    diffRange: 'Beginner - Intermediate',
    whenToUse: 'Use early in breaststroke technique sets before full-stroke timing work.',
    whenNotToUse: 'Hold off when knee width or foot position is the bigger limiter.',
    matchKeywords: ['breaststroke', 'kick timing', 'heel', 'snap', 'glide'],
  },
  {
    id: 'breaststroke-knee-width-control',
    title: 'Breaststroke Knee Width Control',
    stroke: 'Breaststroke',
    phases: ['Kick Recovery', 'Kick Drive'],
    faults: ['Wide knees', 'Knees drop under body', 'Kick finishes wide'],
    objective: 'Keep the recovery narrow and controlled so the swimmer holds a cleaner body line through the kick.',
    primaryCue: 'Heels come up, knees stay inside the hips.',
    cueTheme: 'Narrow recovery, strong foot pressure.',
    bestFor: 'Swimmers whose breaststroke kick creates drag or loses symmetry.',
    equipment: 'Wall, pull buoy, or light band',
    diffRange: 'Beginner - Intermediate',
    whenToUse: 'Use before tempo work or any set where wide knees appear under fatigue.',
    whenNotToUse: 'Avoid forcing range if the swimmer reports knee pain.',
    matchKeywords: ['breaststroke', 'knee width', 'wide knees', 'narrow kick', 'pull buoy'],
  },
  {
    id: 'breaststroke-pull-breath-timing',
    title: 'Breaststroke Pull & Breath Timing',
    stroke: 'Breaststroke',
    phases: ['Pull', 'Breathing', 'Timing'],
    faults: ['Head lifts early', 'Pull too wide', 'Breath breaks rhythm'],
    objective: 'Coordinate the small pull, quick breath, and forward recovery without lifting the body out of line.',
    primaryCue: 'Hands press, eyes rise, shoot forward.',
    cueTheme: 'Small pull, quick breath, forward recovery.',
    bestFor: 'Swimmers who over-pull or breathe late in breaststroke.',
    equipment: 'None or pull buoy',
    diffRange: 'Intermediate',
    whenToUse: 'Use after the kick pattern is stable and before full-stroke race rhythm.',
    whenNotToUse: 'Not first priority if the kick is still uncontrolled.',
    matchKeywords: ['breaststroke', 'pull', 'breath', 'timing', 'shoot forward'],
  },
  {
    id: 'freestyle-body-line',
    title: 'Freestyle Body Line',
    stroke: 'Freestyle',
    phases: ['Body Line', 'Rotation'],
    faults: ['Sinking hips', 'High head', 'Body line breaks while kicking'],
    objective: 'Create a long, quiet body line so the swimmer can hold hips high before adding harder catch work.',
    primaryCue: 'Press the chest, lengthen the spine, let the hips ride high.',
    cueTheme: 'Long vessel, quiet head, high hips.',
    bestFor: 'Freestyle swimmers who fight the water before the catch begins.',
    equipment: 'Fins optional',
    diffRange: 'Beginner - Intermediate',
    whenToUse: 'Use at the start of freestyle technique sessions and after fatigue breaks posture.',
    whenNotToUse: 'Do not overuse if the swimmer already holds stable posture and needs propulsion work.',
    matchKeywords: ['freestyle', 'body line', 'hips', 'head', 'posture'],
  },
  {
    id: 'freestyle-catch-position',
    title: 'Freestyle Catch Position',
    stroke: 'Freestyle',
    phases: ['Catch', 'Pull'],
    faults: ['Dropped elbow', 'Pressing down', 'Slipping water'],
    objective: 'Build an early catch shape with the fingertips down and forearm connected to the water.',
    primaryCue: 'Fingertips down, elbow stays proud.',
    cueTheme: 'Feel pressure on hand and forearm before pulling.',
    bestFor: 'Swimmers with weak propulsion or an elbow that collapses at the front.',
    equipment: 'Snorkel, paddles optional',
    diffRange: 'Intermediate - Advanced',
    whenToUse: 'Use at low to moderate intensity where the swimmer can feel water pressure.',
    whenNotToUse: 'Avoid heavy paddles if the swimmer cannot hold the shape without them.',
    matchKeywords: ['freestyle', 'catch', 'elbow', 'forearm', 'scull'],
  },
  {
    id: 'freestyle-breathing-control',
    title: 'Freestyle Breathing Control',
    stroke: 'Freestyle',
    phases: ['Breathing', 'Rotation'],
    faults: ['Head lifts to breathe', 'Over-rotation', 'Late breath'],
    objective: 'Keep the breath low and connected to rotation so the body line stays intact.',
    primaryCue: 'One goggle in, one goggle out.',
    cueTheme: 'Low breath, stable lead arm, smooth return.',
    bestFor: 'Swimmers whose hips drop or rhythm breaks every time they breathe.',
    equipment: 'Fins optional',
    diffRange: 'Beginner - Intermediate',
    whenToUse: 'Use in aerobic technique work before adding speed.',
    whenNotToUse: 'Avoid breath-control pressure for anxious or very new swimmers.',
    matchKeywords: ['freestyle', 'breathing', 'one goggle', 'rotation', 'head'],
  },
  {
    id: 'backstroke-hip-position',
    title: 'Backstroke Hip Position',
    stroke: 'Backstroke',
    phases: ['Body Line', 'Rotation', 'Kick Drive'],
    faults: ['Dropped hips', 'Knees break surface', 'Flat body position'],
    objective: 'Hold a high-hip backstroke line with steady rotation and a compact kick.',
    primaryCue: 'Belly up, hips high, kick under the surface.',
    cueTheme: 'Tall posture on the back with quiet knees.',
    bestFor: 'Backstrokers who sit low or kick from the knees.',
    equipment: 'Fins, cup optional',
    diffRange: 'Beginner - Intermediate',
    whenToUse: 'Use early in backstroke blocks and after hard sets when posture collapses.',
    whenNotToUse: 'Do not chase speed until the swimmer can hold the line.',
    matchKeywords: ['backstroke', 'hip', 'body line', 'kick', 'rotation'],
  },
  {
    id: 'butterfly-rhythm-body-wave',
    title: 'Butterfly Rhythm & Body Wave',
    stroke: 'Butterfly',
    phases: ['Timing', 'Body Line', 'Breathing'],
    faults: ['Flat body wave', 'Late second kick', 'High breath'],
    objective: 'Connect body wave, two-beat kick timing, and low breath position without forcing the stroke.',
    primaryCue: 'Kick in, kick out, breathe low.',
    cueTheme: 'Rhythm first, power second.',
    bestFor: 'Swimmers who muscle butterfly instead of riding the rhythm.',
    equipment: 'Fins recommended',
    diffRange: 'Intermediate - Advanced',
    whenToUse: 'Use with short repeats and plenty of rest so rhythm stays clean.',
    whenNotToUse: 'Avoid long fatigue sets while rebuilding timing.',
    matchKeywords: ['butterfly', 'body wave', 'rhythm', 'dolphin', 'second kick'],
  },
  {
    id: 'streamline-starts-turns',
    title: 'Streamline / Starts / Turns',
    stroke: 'General',
    phases: ['Start', 'Turn', 'Underwater', 'Breakout'],
    faults: ['Loose streamline', 'Early breakout', 'Weak push-off'],
    objective: 'Improve wall speed, underwater line, and breakout timing across all strokes.',
    primaryCue: 'Lock the line before you leave the wall.',
    cueTheme: 'Tight streamline, patient breakout, fast first stroke.',
    bestFor: 'Any competitive swimmer losing speed off starts or turns.',
    equipment: 'None or fins',
    diffRange: 'Beginner - Elite',
    whenToUse: 'Use every week in small doses, especially before race preparation.',
    whenNotToUse: 'Keep volume low for younger swimmers who cannot hold breath comfortably.',
    matchKeywords: ['streamline', 'start', 'turn', 'underwater', 'breakout'],
  },
];

const drill = ({
  id,
  title,
  stroke,
  phase,
  pack_ids,
  fault_tags,
  purpose,
  coaching_cue,
  setup,
  execution_steps,
  common_mistakes,
  progression,
  report_summary,
  difficulty = 'Intermediate',
  equipment = 'none',
  duration_or_reps = '4 x 25m easy technique',
  regression = '',
  when_to_use = '',
  three_d_demo_status = 'coming_later',
  safety_notes = 'None.',
}) => ({
  id,
  title,
  stroke,
  phase,
  pack_ids,
  fault_tags,
  purpose,
  coaching_cue,
  coaching_cues: coaching_cue,
  setup,
  execution_steps,
  instructions: execution_steps.join(' '),
  common_mistakes,
  progression,
  report_summary: report_summary || purpose,
  regression,
  difficulty,
  equipment,
  duration_or_reps,
  when_to_use: when_to_use || `Use when ${fault_tags.split(',')[0].trim()} is limiting the swimmer's next technical step.`,
  three_d_demo_status,
  safety_notes,
  is_default: true,
  is_active: true,
  visibility: 'shared_default',
  club_id: null,
});

export const DEFAULT_DRILLS = [
  drill({
    id: 'bs-heel-recovery-pause',
    title: 'Heel Recovery Pause Kick',
    stroke: 'Breaststroke',
    phase: 'Kick Recovery',
    pack_ids: ['breaststroke-kick-timing'],
    fault_tags: 'kick timing, heel recovery, early foot turn, breaststroke',
    purpose: 'Teaches swimmers to bring the heels up before turning the feet out.',
    coaching_cue: 'Heels first, feet turn last.',
    setup: 'Hold the wall or use a kickboard at easy effort.',
    execution_steps: ['Recover heels slowly to the seat.', 'Pause for one count.', 'Turn feet out and snap together.', 'Glide for one beat before repeating.'],
    common_mistakes: 'Turning the feet before the heels rise|Rushing the snap|Letting knees drift wide',
    progression: 'Remove the pause and keep the same sequence at normal rhythm.',
    difficulty: 'Beginner',
    equipment: 'wall or board',
  }),
  drill({
    id: 'bs-kick-glide-count',
    title: 'Kick-Glide Count Drill',
    stroke: 'Breaststroke',
    phase: 'Timing',
    pack_ids: ['breaststroke-kick-timing'],
    fault_tags: 'kick timing, glide, rushed kick, breaststroke',
    purpose: 'Connects a clean kick finish to a short controlled glide.',
    coaching_cue: 'Snap, squeeze, ride the line.',
    setup: 'Push off in streamline and work at low speed.',
    execution_steps: ['Complete one breaststroke kick.', 'Squeeze feet together.', 'Count one beat in glide.', 'Repeat without adding a pull.'],
    common_mistakes: 'No glide after the kick|Looking forward|Letting feet separate after the snap',
    progression: 'Move to full stroke with the same one-beat glide.',
    difficulty: 'Beginner',
  }),
  drill({
    id: 'bs-2-kicks-1-pull',
    title: 'Two Kicks One Pull',
    stroke: 'Breaststroke',
    phase: 'Timing',
    pack_ids: ['breaststroke-kick-timing', 'breaststroke-pull-breath-timing'],
    fault_tags: 'kick timing, pull timing, glide, breaststroke',
    purpose: 'Gives extra time to feel kick completion before the next pull.',
    coaching_cue: 'Finish both kicks before the hands move.',
    setup: 'Swim breaststroke with two kicks for every arm pull.',
    execution_steps: ['Pull and breathe once.', 'Recover forward.', 'Complete two controlled kicks.', 'Start the next pull only after the second glide.'],
    common_mistakes: 'Starting the pull during the kick|Over-gliding until speed stops|Lifting the head between kicks',
    progression: 'Alternate 25m two-kick drill with 25m full stroke.',
    equipment: 'none',
  }),
  drill({
    id: 'bs-snap-finish-line',
    title: 'Snap Finish Line Drill',
    stroke: 'Breaststroke',
    phase: 'Kick Drive',
    pack_ids: ['breaststroke-kick-timing'],
    fault_tags: 'weak snap, kick finish, breaststroke kick',
    purpose: 'Sharpens the final squeeze of the feet so the kick finishes narrow and fast.',
    coaching_cue: 'Snap the heels together behind the line.',
    setup: 'Use short repeats with full rest.',
    execution_steps: ['Kick breaststroke on front or back.', 'Focus only on the final foot snap.', 'Finish with toes pointed and legs long.', 'Reset before the next kick.'],
    common_mistakes: 'Soft finish|Feet finishing apart|Bending knees again after the snap',
    progression: 'Add full stroke while keeping the same kick finish.',
    difficulty: 'Intermediate',
  }),
  drill({
    id: 'bs-wall-narrow-kick',
    title: 'Wall Narrow-Knee Kick',
    stroke: 'Breaststroke',
    phase: 'Kick Recovery',
    pack_ids: ['breaststroke-knee-width-control'],
    fault_tags: 'wide knees, knee width, narrow kick, breaststroke',
    purpose: 'Creates visual feedback for knee width during kick recovery.',
    coaching_cue: 'Knees inside the hips.',
    setup: 'Face the wall with hands on the gutter.',
    execution_steps: ['Set hips close to the surface.', 'Recover heels without flaring knees.', 'Watch knee width against the body line.', 'Snap and squeeze feet together.'],
    common_mistakes: 'Knees opening wider than hips|Hips dropping|Pulling knees under the belly',
    progression: 'Move from wall to kickboard while keeping the same width.',
    difficulty: 'Beginner',
    equipment: 'wall',
  }),
  drill({
    id: 'bs-pull-buoy-knee-track',
    title: 'Pull Buoy Knee Track Kick',
    stroke: 'Breaststroke',
    phase: 'Kick Recovery',
    pack_ids: ['breaststroke-knee-width-control'],
    fault_tags: 'wide knees, knee control, pull buoy, breaststroke kick',
    purpose: 'Gives immediate feedback when the knees separate too much.',
    coaching_cue: 'Hold the buoy lightly, kick from the feet.',
    setup: 'Place a small pull buoy between the knees.',
    execution_steps: ['Keep light contact with the buoy.', 'Recover heels slowly.', 'Turn feet out without squeezing hard.', 'Snap and return to a long line.'],
    common_mistakes: 'Crushing the buoy|Losing foot pressure|Cycling the knees forward',
    progression: 'Remove the buoy and repeat the same narrow recovery.',
    equipment: 'pull buoy',
  }),
  drill({
    id: 'bs-back-kick-line',
    title: 'Back Breaststroke Kick Line',
    stroke: 'Breaststroke',
    phase: 'Kick Drive',
    pack_ids: ['breaststroke-knee-width-control'],
    fault_tags: 'knee width, kick path, asymmetric kick, breaststroke',
    purpose: 'Lets the coach see the kick path and helps the swimmer feel foot pressure.',
    coaching_cue: 'Show the soles, then squeeze the line.',
    setup: 'Swim on the back with arms by side or streamlined.',
    execution_steps: ['Recover heels under the water.', 'Keep knees from popping wide.', 'Press soles back against the water.', 'Finish long and narrow.'],
    common_mistakes: 'Knees breaking high|Feet missing water|Uneven kick finish',
    progression: 'Alternate back kick and normal breaststroke kick.',
    difficulty: 'Intermediate',
  }),
  drill({
    id: 'bs-band-awareness-kick',
    title: 'Light Band Awareness Kick',
    stroke: 'Breaststroke',
    phase: 'Kick Recovery',
    pack_ids: ['breaststroke-knee-width-control'],
    fault_tags: 'wide knees, hip control, knee width, breaststroke',
    purpose: 'Builds awareness of excessive knee separation without forcing the joint.',
    coaching_cue: 'Feel the band, do not fight it.',
    setup: 'Use a light band above the knees only with coach supervision.',
    execution_steps: ['Kick slowly for short repeats.', 'Keep band tension light.', 'Recover heels without pushing knees outward.', 'Stop if knee discomfort appears.'],
    common_mistakes: 'Using a band that is too tight|Forcing range|Ignoring knee discomfort',
    progression: 'Remove the band and keep the same recovery path.',
    difficulty: 'Advanced',
    equipment: 'light band',
    safety_notes: 'Stop immediately if the swimmer reports knee pain.',
  }),
  drill({
    id: 'bs-small-pull-breath',
    title: 'Small Pull Breath Drill',
    stroke: 'Breaststroke',
    phase: 'Pull',
    pack_ids: ['breaststroke-pull-breath-timing'],
    fault_tags: 'over-pull, breath timing, breaststroke pull',
    purpose: 'Prevents the pull from sweeping too wide or too far back.',
    coaching_cue: 'Small heart shape, quick breath.',
    setup: 'Swim easy breaststroke focusing on arm path only.',
    execution_steps: ['Press out slightly.', 'Sweep in under the chin.', 'Breathe as the hands gather.', 'Shoot hands forward before kicking.'],
    common_mistakes: 'Pulling past the shoulders|Breathing after the hands recover|Dropping elbows',
    progression: 'Add tempo while keeping the pull small.',
  }),
  drill({
    id: 'bs-shoot-forward',
    title: 'Shoot Forward Recovery',
    stroke: 'Breaststroke',
    phase: 'Recovery',
    pack_ids: ['breaststroke-pull-breath-timing'],
    fault_tags: 'slow recovery, breath timing, dropped hips, breaststroke',
    purpose: 'Trains a fast forward hand recovery after the breath.',
    coaching_cue: 'Breathe, then shoot the hands to the wall.',
    setup: 'Use short 12.5m or 25m repeats.',
    execution_steps: ['Start the pull small.', 'Take a quick breath.', 'Drive both hands forward together.', 'Let the kick finish the line.'],
    common_mistakes: 'Pausing under the chin|Throwing the head up|Hands diving too deep',
    progression: 'Use a slightly faster tempo without losing line.',
  }),
  drill({
    id: 'bs-pull-kick-separate',
    title: 'Pull-Kick Separation Drill',
    stroke: 'Breaststroke',
    phase: 'Timing',
    pack_ids: ['breaststroke-pull-breath-timing'],
    fault_tags: 'pull timing, kick timing, rushed rhythm, breaststroke',
    purpose: 'Separates the actions so the swimmer stops pulling and kicking at the same time.',
    coaching_cue: 'Pull first, kick second.',
    setup: 'Swim slowly with a deliberate rhythm.',
    execution_steps: ['Pull and breathe.', 'Recover the hands fully forward.', 'Then kick and glide.', 'Repeat with quiet head position.'],
    common_mistakes: 'Kicking while the hands are still under the body|Over-gliding|Rushing the breath',
    progression: 'Reduce the pause until the timing becomes full-stroke rhythm.',
    difficulty: 'Beginner',
  }),
  drill({
    id: 'bs-low-breath-line',
    title: 'Low Breath Line Drill',
    stroke: 'Breaststroke',
    phase: 'Breathing',
    pack_ids: ['breaststroke-pull-breath-timing'],
    fault_tags: 'high breath, head lift, dropped hips, breaststroke',
    purpose: 'Keeps the breath forward and low so the hips do not drop.',
    coaching_cue: 'Eyes forward, chin low, hands forward.',
    setup: 'Swim at easy effort with coach watching from the side.',
    execution_steps: ['Let the pull lift the breath.', 'Keep the chin close to the surface.', 'Return eyes down as hands shoot forward.', 'Kick after the hands recover.'],
    common_mistakes: 'Looking at the end wall|Breathing too late|Arching the back',
    progression: 'Alternate drill lengths with normal breaststroke.',
  }),
  drill({
    id: 'bs-slow-2-count-kick',
    title: 'Slow 2-Count Kick: Heels Up, Turn, Drive',
    stroke: 'Breaststroke',
    phase: 'Kick Recovery',
    pack_ids: ['breaststroke-kick-timing', 'breaststroke-knee-width-control'],
    fault_tags: 'heel recovery, early foot turn, low heels, wide knees, breaststroke kick',
    purpose: 'Slows the kick sequence down so the swimmer can separate heel recovery, late foot turn, and backward drive.',
    report_summary: 'Builds a cleaner breaststroke kick sequence: heels recover first, feet turn late, then the kick drives straight back.',
    coaching_cue: 'Heels up first, turn late, drive back.',
    setup: 'Use a board or wall support and keep the repeat distance short.',
    execution_steps: ['Recover heels for count one.', 'Turn the feet out only after the heels are set.', 'Drive the feet back and squeeze the line on count two.', 'Reset slowly before the next kick.'],
    common_mistakes: 'Turning the feet too early|Letting knees flare outside hips|Pressing the kick downward instead of backward',
    progression: 'Move from slow count to normal kick rhythm without losing the sequence.',
    difficulty: 'Beginner',
    equipment: 'board or wall',
  }),
  drill({
    id: 'bs-3-second-line-hold',
    title: 'Breaststroke Kick Into 3-Second Line Hold',
    stroke: 'Breaststroke',
    phase: 'Kick Drive',
    pack_ids: ['breaststroke-kick-timing', 'breaststroke-knee-width-control'],
    fault_tags: 'weak line reset, rushed glide, kick pressing down, dropped hips, breaststroke',
    purpose: 'Rewards a narrow kick finish by making the swimmer hold the line after the feet snap together.',
    report_summary: 'Helps the swimmer feel the line after the kick instead of rushing into the next pull.',
    coaching_cue: 'Kick, squeeze, hold the line.',
    setup: 'Push off in streamline or use a board at easy effort.',
    execution_steps: ['Complete one controlled breaststroke kick.', 'Squeeze ankles together behind the body.', 'Hold a long line for three seconds.', 'Repeat only while the body stays level.'],
    common_mistakes: 'Starting the next action too soon|Feet finishing apart|Head lifting during the hold',
    progression: 'Reduce the hold to one beat and transfer the same line reset into full stroke.',
    difficulty: 'Beginner',
  }),
  drill({
    id: 'bs-narrow-knee-kick-on-back',
    title: 'Narrow-Knee Kick on Back',
    stroke: 'Breaststroke',
    phase: 'Kick Recovery',
    pack_ids: ['breaststroke-knee-width-control'],
    fault_tags: 'wide knees, low heel recovery, asymmetric kick, knee width, breaststroke',
    purpose: 'Gives the swimmer and coach a clear view of knee width and foot path during the recovery.',
    report_summary: 'Makes wide knees easier to see and correct while the swimmer learns to recover heels without losing line.',
    coaching_cue: 'Heels recover under the hips, knees stay quiet.',
    setup: 'Swim on the back with arms by side or in streamline.',
    execution_steps: ['Set hips high near the surface.', 'Recover heels without popping the knees wide.', 'Turn feet out late.', 'Snap and finish with legs long and narrow.'],
    common_mistakes: 'Knees breaking high above the water|Feet missing pressure|Arching the back to compensate',
    progression: 'Alternate 12.5m on back with 12.5m normal breaststroke kick.',
    difficulty: 'Intermediate',
  }),
  drill({
    id: 'bs-fast-hand-recovery-pull',
    title: 'Breaststroke Pull With Fast Hand Recovery',
    stroke: 'Breaststroke',
    phase: 'Recovery',
    pack_ids: ['breaststroke-pull-breath-timing'],
    fault_tags: 'slow hands, poor breath timing, hands stuck under chin, dropped hips, breaststroke pull',
    purpose: 'Trains the hands to recover forward quickly after the breath so the swimmer returns to line before the kick.',
    report_summary: 'Encourages a quick hand shoot-forward so the breath does not stall the stroke.',
    coaching_cue: 'Breathe, then shoot the hands forward.',
    setup: 'Use relaxed 25m repeats with the coach watching from the side.',
    execution_steps: ['Keep the pull small.', 'Breathe as the hands gather.', 'Drive the hands forward together.', 'Kick only after the hands are back in front.'],
    common_mistakes: 'Pausing under the chin|Diving the hands too deep|Kicking before the hands recover',
    progression: 'Add race rhythm while keeping the same fast recovery.',
    difficulty: 'Intermediate',
  }),
  drill({
    id: 'bs-glide-timing-reset',
    title: 'Glide Timing Reset Drill',
    stroke: 'Breaststroke',
    phase: 'Timing',
    pack_ids: ['breaststroke-kick-timing', 'breaststroke-pull-breath-timing'],
    fault_tags: 'rushed glide, timing break, weak line reset, pull timing, breaststroke',
    purpose: 'Resets the pull-kick-glide rhythm so the swimmer feels forward movement before starting the next stroke.',
    report_summary: 'Rebuilds breaststroke timing around a controlled line reset instead of a rushed next pull.',
    coaching_cue: 'Pull, kick, ride the line.',
    setup: 'Swim easy breaststroke with a deliberate short glide after each kick.',
    execution_steps: ['Pull and breathe smoothly.', 'Recover hands forward.', 'Kick and finish narrow.', 'Hold the line just long enough to feel forward travel.'],
    common_mistakes: 'Waiting until speed stops|Pulling before the kick finishes|Looking forward during the glide',
    progression: 'Use a tempo trainer or coach count to shorten the glide without rushing.',
    difficulty: 'Intermediate',
  }),
  drill({
    id: 'fr-streamline-kick',
    title: 'Streamline Flutter Kick',
    stroke: 'Freestyle',
    phase: 'Body Line',
    pack_ids: ['freestyle-body-line', 'streamline-starts-turns'],
    fault_tags: 'body line, sinking hips, high head, freestyle',
    purpose: 'Builds a long freestyle line without arm timing distractions.',
    coaching_cue: 'Long neck, ribs quiet, hips high.',
    setup: 'Push off in streamline and kick easy.',
    execution_steps: ['Lock hands in streamline.', 'Look down.', 'Kick small from the hips.', 'Hold the body line until speed fades.'],
    common_mistakes: 'Kicking from the knees|Looking forward|Arching the lower back',
    progression: 'Add six kicks then one stroke while preserving the line.',
    difficulty: 'Beginner',
  }),
  drill({
    id: 'fr-side-kick-switch',
    title: 'Side Kick Switch',
    stroke: 'Freestyle',
    phase: 'Rotation',
    pack_ids: ['freestyle-body-line', 'freestyle-breathing-control'],
    fault_tags: 'rotation, body line, balance, freestyle',
    purpose: 'Develops balance on each side of the freestyle rotation.',
    coaching_cue: 'Long lead arm, hip points to the wall.',
    setup: 'Kick on one side with bottom arm extended.',
    execution_steps: ['Hold six kicks on one side.', 'Take one smooth stroke to switch.', 'Hold six kicks on the other side.', 'Keep the head still unless breathing.'],
    common_mistakes: 'Rolling onto the back|Lead arm dropping|Scissor kick during switch',
    progression: 'Use 6-3-6 with three full strokes between sides.',
    equipment: 'fins optional',
  }),
  drill({
    id: 'fr-head-still-kick',
    title: 'Head-Still Kick With Board',
    stroke: 'Freestyle',
    phase: 'Body Line',
    pack_ids: ['freestyle-body-line'],
    fault_tags: 'high head, sinking hips, body line, freestyle',
    purpose: 'Shows how head position affects hip height.',
    coaching_cue: 'Eyes down, water over the cap.',
    setup: 'Use a board lightly, not as a flotation crutch.',
    execution_steps: ['Hold the board low in the water.', 'Look down between the arms.', 'Kick small and steady.', 'Keep hips near the surface.'],
    common_mistakes: 'Pressing down on the board|Looking forward|Large knee bend',
    progression: 'Remove the board and repeat in streamline.',
    difficulty: 'Beginner',
    equipment: 'board',
  }),
  drill({
    id: 'fr-line-to-catch',
    title: 'Body Line To Catch',
    stroke: 'Freestyle',
    phase: 'Body Line',
    pack_ids: ['freestyle-body-line', 'freestyle-catch-position'],
    fault_tags: 'body line, catch setup, freestyle',
    purpose: 'Connects posture to a stable front-end catch.',
    coaching_cue: 'Set the line before you press the water.',
    setup: 'Swim slow freestyle with a brief front-end extension.',
    execution_steps: ['Reach forward without dropping the wrist.', 'Hold the body line for half a beat.', 'Tip fingertips down into catch.', 'Pull only after pressure builds.'],
    common_mistakes: 'Pausing too long|Crossing over|Pressing down instead of catching',
    progression: 'Remove the pause and keep the same catch setup.',
  }),
  drill({
    id: 'fr-front-scull',
    title: 'Front Scull',
    stroke: 'Freestyle',
    phase: 'Catch',
    pack_ids: ['freestyle-catch-position'],
    fault_tags: 'catch, feel for water, forearm pressure, freestyle',
    purpose: 'Builds hand and forearm awareness at the start of the catch.',
    coaching_cue: 'Feel pressure, do not push down.',
    setup: 'Use a snorkel if available to keep the head quiet.',
    execution_steps: ['Extend arms in front.', 'Angle fingertips slightly down.', 'Sweep hands in and out small.', 'Keep elbows higher than hands.'],
    common_mistakes: 'Large sweeping motions|Dropping elbows|Kicking too hard',
    progression: 'Scull for six beats, then swim six strokes.',
    equipment: 'snorkel optional',
  }),
  drill({
    id: 'fr-fist-drill',
    title: 'Fist Drill',
    stroke: 'Freestyle',
    phase: 'Catch',
    pack_ids: ['freestyle-catch-position'],
    fault_tags: 'catch, forearm, slipping water, freestyle',
    purpose: 'Forces the swimmer to use the forearm rather than only the hand.',
    coaching_cue: 'Hold water with the whole forearm.',
    setup: 'Swim freestyle with closed fists.',
    execution_steps: ['Close both fists lightly.', 'Keep the elbow high during catch.', 'Feel pressure on forearm.', 'Open hands after 12.5m and compare feel.'],
    common_mistakes: 'Spinning arms faster|Dropping the elbow|Losing body line',
    progression: 'Alternate fist drill and normal swim by 25m.',
    difficulty: 'Beginner',
  }),
  drill({
    id: 'fr-single-arm-catch',
    title: 'Single Arm Catch Hold',
    stroke: 'Freestyle',
    phase: 'Pull',
    pack_ids: ['freestyle-catch-position'],
    fault_tags: 'catch position, high elbow, pull path, freestyle',
    purpose: 'Lets the swimmer focus on one catch shape at a time.',
    coaching_cue: 'Anchor first, then move past the hand.',
    setup: 'One arm extended, one arm stroking; breathe to the stroking side as needed.',
    execution_steps: ['Hold the lead arm long.', 'Tip fingertips down.', 'Keep elbow above hand.', 'Pull past the anchor point.'],
    common_mistakes: 'Lead arm sinking|Pulling straight down|Over-rotating to breathe',
    progression: 'Switch to three strokes right, three strokes left.',
    equipment: 'fins optional',
  }),
  drill({
    id: 'fr-evf-paddle-tap',
    title: 'EVF Paddle Tap',
    stroke: 'Freestyle',
    phase: 'Catch',
    pack_ids: ['freestyle-catch-position'],
    fault_tags: 'early vertical forearm, dropped elbow, catch, freestyle',
    purpose: 'Uses light paddle feedback to keep the fingertips pitched down.',
    coaching_cue: 'Show the paddle face to the wall behind you.',
    setup: 'Use small paddles only if the swimmer can hold shape safely.',
    execution_steps: ['Swim slowly with small paddles.', 'Set the catch before force.', 'Keep elbow proud.', 'Stop if shoulder discomfort appears.'],
    common_mistakes: 'Using large paddles|Muscling the pull|Losing rotation',
    progression: 'Remove paddles and keep the same hand angle.',
    difficulty: 'Advanced',
    equipment: 'small paddles',
    safety_notes: 'Avoid paddles for swimmers with shoulder pain.',
  }),
  drill({
    id: 'fr-one-goggle-breath',
    title: 'One-Goggle Breath',
    stroke: 'Freestyle',
    phase: 'Breathing',
    pack_ids: ['freestyle-breathing-control'],
    fault_tags: 'breathing, head lift, low breath, freestyle',
    purpose: 'Keeps the breath low so the head does not lift and sink the hips.',
    coaching_cue: 'One goggle in, one goggle out.',
    setup: 'Swim easy freestyle breathing every three or four strokes.',
    execution_steps: ['Rotate the head with the body.', 'Keep one lens in the water.', 'Return the face before the stroking arm enters.', 'Keep the lead arm patient.'],
    common_mistakes: 'Lifting to breathe|Looking backward|Dropping the lead arm',
    progression: 'Use the same breath at moderate pace.',
    difficulty: 'Beginner',
  }),
  drill({
    id: 'fr-bubble-bubble-breathe',
    title: 'Bubble-Bubble-Breathe',
    stroke: 'Freestyle',
    phase: 'Breathing',
    pack_ids: ['freestyle-breathing-control'],
    fault_tags: 'breath timing, exhale, freestyle breathing',
    purpose: 'Teaches steady exhale so the breath can stay quick and low.',
    coaching_cue: 'Blow before you go.',
    setup: 'Use relaxed 25m repeats.',
    execution_steps: ['Exhale steadily for two strokes.', 'Turn to breathe without pausing.', 'Return face down immediately.', 'Resume bubbles before the next breath.'],
    common_mistakes: 'Holding breath underwater|Breathing late|Over-rotating',
    progression: 'Add bilateral breathing if appropriate.',
  }),
  drill({
    id: 'fr-breath-with-fins',
    title: 'Fins Low-Breath Rhythm',
    stroke: 'Freestyle',
    phase: 'Breathing',
    pack_ids: ['freestyle-breathing-control'],
    fault_tags: 'breathing rhythm, body line, freestyle',
    purpose: 'Uses fins to support speed while the swimmer focuses on calm breathing.',
    coaching_cue: 'Let the body roll the breath open.',
    setup: 'Wear fins and swim at controlled aerobic effort.',
    execution_steps: ['Kick steady from the hips.', 'Rotate to breathe with one goggle in.', 'Keep the lead arm extended.', 'Return to line before the next catch.'],
    common_mistakes: 'Kicking too hard|Pausing the lead arm too long|Lifting the chin',
    progression: 'Remove fins and repeat short repeats.',
    equipment: 'fins',
  }),
  drill({
    id: 'fr-breath-reset-6-1-6',
    title: '6-1-6 Breath Reset',
    stroke: 'Freestyle',
    phase: 'Breathing',
    pack_ids: ['freestyle-breathing-control', 'freestyle-body-line'],
    fault_tags: 'breathing, rotation, balance, freestyle',
    purpose: 'Links side balance with a controlled breath and stroke switch.',
    coaching_cue: 'Breathe from the side balance, not from a lift.',
    setup: 'Kick six beats on one side, stroke once, then switch.',
    execution_steps: ['Start on side with one arm extended.', 'Take one low breath.', 'Stroke once to switch sides.', 'Repeat on the other side.'],
    common_mistakes: 'Rolling onto back|Lead arm sinking|Kick stopping during breath',
    progression: 'Move to 6-3-6 with three strokes between sides.',
    equipment: 'fins optional',
  }),
  drill({
    id: 'fr-catch-up-controlled-rotation',
    title: 'Catch-Up With Controlled Rotation',
    stroke: 'Freestyle',
    phase: 'Rotation',
    pack_ids: ['freestyle-body-line', 'freestyle-catch-position'],
    fault_tags: 'crossover entry, flat rotation, over rotation, short extension, freestyle',
    purpose: 'Slows freestyle down enough for the swimmer to place the hand in line with the shoulder and rotate without crossing over.',
    report_summary: 'Helps the swimmer connect a patient front-end extension with controlled body rotation.',
    coaching_cue: 'Reach shoulder-width, rotate around the line.',
    setup: 'Swim catch-up freestyle at easy effort; use a snorkel if breathing disrupts the line.',
    execution_steps: ['Hold one arm extended in front.', 'Recover the other arm and enter shoulder-width.', 'Switch only once the lead hand is stable.', 'Keep the head quiet through the rotation.'],
    common_mistakes: 'Touching hands across the midline|Pausing until speed dies|Rolling too far onto the side',
    progression: 'Move to three-quarter catch-up, then normal freestyle with the same entry line.',
    difficulty: 'Beginner',
    equipment: 'snorkel optional',
  }),
  drill({
    id: 'fr-side-kick-breathing-drill',
    title: 'Side-Kick Breathing Drill',
    stroke: 'Freestyle',
    phase: 'Breathing',
    pack_ids: ['freestyle-breathing-control', 'freestyle-body-line'],
    fault_tags: 'head lifting on breath, low breath, legs dropping, lead arm dropping, freestyle',
    purpose: 'Teaches the swimmer to breathe from side balance instead of lifting the head.',
    report_summary: 'Builds a low breath while preserving lead-arm support and high hips.',
    coaching_cue: 'Breathe from the side, not by lifting.',
    setup: 'Kick on the side with one arm extended and one arm resting at the hip.',
    execution_steps: ['Hold a long side line.', 'Turn the mouth to air with one goggle low.', 'Return the face calmly.', 'Switch sides after 6 to 8 kicks.'],
    common_mistakes: 'Lifting the chin|Letting the lead arm sink|Stopping the kick during the breath',
    progression: 'Add one freestyle stroke between side-kick positions.',
    difficulty: 'Beginner',
    equipment: 'fins optional',
  }),
  drill({
    id: 'fr-paddle-free-catch-pressure',
    title: 'Paddle-Free Catch Pressure Drill',
    stroke: 'Freestyle',
    phase: 'Catch',
    pack_ids: ['freestyle-catch-position'],
    fault_tags: 'dropped elbow, weak catch, slipping water, pressing down, freestyle',
    purpose: 'Builds catch pressure without relying on paddles, so the swimmer learns to hold water safely with the hand and forearm.',
    report_summary: 'Develops a safer catch feel by asking the swimmer to find pressure before adding force.',
    coaching_cue: 'Set pressure before power.',
    setup: 'Swim slow freestyle or front scull without paddles.',
    execution_steps: ['Extend forward with a relaxed hand.', 'Tip fingertips down.', 'Hold the elbow higher than the hand.', 'Press back only once pressure is felt.'],
    common_mistakes: 'Pushing down to lift the body|Rushing the pull|Forcing the shoulder',
    progression: 'Add normal freestyle strokes after 6 scull beats.',
    difficulty: 'Intermediate',
  }),
  drill({
    id: 'bk-cup-balance',
    title: 'Backstroke Cup Balance',
    stroke: 'Backstroke',
    phase: 'Body Line',
    pack_ids: ['backstroke-hip-position'],
    fault_tags: 'head stability, dropped hips, backstroke body line',
    purpose: 'Encourages still head position so the hips can stay high.',
    coaching_cue: 'Eyes still, belly up.',
    setup: 'Place a small plastic cup on the forehead if safe and appropriate.',
    execution_steps: ['Float tall on the back.', 'Kick gently under the surface.', 'Keep eyes fixed upward.', 'Swim without spilling the cup.'],
    common_mistakes: 'Tucking the chin|Knees breaking the surface|Over-kicking',
    progression: 'Remove the cup and keep the same head position.',
    difficulty: 'Beginner',
    equipment: 'cup optional',
  }),
  drill({
    id: 'bk-hip-lift-kick',
    title: 'Backstroke Hip-Lift Kick',
    stroke: 'Backstroke',
    phase: 'Kick Drive',
    pack_ids: ['backstroke-hip-position'],
    fault_tags: 'dropped hips, knee kick, backstroke',
    purpose: 'Shows the swimmer how to keep hips near the surface while kicking.',
    coaching_cue: 'Push the belt buckle to the sky.',
    setup: 'Arms by side or streamlined on back.',
    execution_steps: ['Set the head still.', 'Lift hips gently toward the surface.', 'Kick small from the hips.', 'Keep knees below the surface.'],
    common_mistakes: 'Bending knees too much|Arching the back|Holding breath',
    progression: 'Add single-arm backstroke while keeping hips high.',
  }),
  drill({
    id: 'bk-rotation-kick',
    title: 'Backstroke Rotation Kick',
    stroke: 'Backstroke',
    phase: 'Rotation',
    pack_ids: ['backstroke-hip-position'],
    fault_tags: 'flat body, hip position, backstroke rotation',
    purpose: 'Connects hip position to controlled shoulder rotation.',
    coaching_cue: 'Rotate around a tall spine.',
    setup: 'Kick on back with one shoulder slightly lifted.',
    execution_steps: ['Hold six kicks rotated to one side.', 'Switch through the middle without lifting the head.', 'Hold six kicks on the other side.', 'Keep hips near the surface.'],
    common_mistakes: 'Head turning with shoulders|Hips sinking during switch|Wide kick',
    progression: 'Add three backstroke pulls between rotations.',
    equipment: 'fins optional',
  }),
  drill({
    id: 'bk-single-arm-posture',
    title: 'Single-Arm Backstroke Posture',
    stroke: 'Backstroke',
    phase: 'Entry',
    pack_ids: ['backstroke-hip-position'],
    fault_tags: 'backstroke posture, dropped hips, rotation',
    purpose: 'Allows one-arm focus while preserving the high-hip line.',
    coaching_cue: 'Reach long without sitting down.',
    setup: 'One arm stays at side while the other strokes.',
    execution_steps: ['Set a tall body line.', 'Stroke one arm with smooth rotation.', 'Keep the kick compact.', 'Switch arms after 12.5m or 25m.'],
    common_mistakes: 'Sitting during recovery|Crossing over|Kicking wider to balance',
    progression: 'Return to full backstroke with the same posture.',
  }),
  drill({
    id: 'bk-6-kick-switch',
    title: '6-Kick Switch Backstroke',
    stroke: 'Backstroke',
    phase: 'Rotation',
    pack_ids: ['backstroke-hip-position'],
    fault_tags: 'under rotation, over rotation, moving head, weak kick rhythm, backstroke',
    purpose: 'Gives the swimmer time to feel each rotated side while the head and hips stay steady.',
    report_summary: 'Builds controlled backstroke rotation without letting the head or hips wander.',
    coaching_cue: 'Switch around a still head.',
    setup: 'Kick on the back with one arm extended and one arm at the side.',
    execution_steps: ['Hold six kicks rotated to one side.', 'Switch arms smoothly through the middle.', 'Hold six kicks on the other side.', 'Keep the face and hips stable.'],
    common_mistakes: 'Turning the head with the shoulders|Dropping hips during the switch|Kicking wide to balance',
    progression: 'Move to 6-3-6 backstroke, then full stroke.',
    difficulty: 'Beginner',
    equipment: 'fins optional',
  }),
  drill({
    id: 'bk-catch-scull',
    title: 'Backstroke Catch Scull',
    stroke: 'Backstroke',
    phase: 'Catch',
    pack_ids: ['backstroke-hip-position'],
    fault_tags: 'shallow catch, slipping water, straight-arm pull, weak catch, backstroke',
    purpose: 'Builds awareness of the backstroke catch with the hand and forearm under the surface.',
    report_summary: 'Helps the swimmer feel water pressure before pulling through backstroke.',
    coaching_cue: 'Bend, hold, then press.',
    setup: 'Float on the back with one arm overhead or both arms near catch position.',
    execution_steps: ['Set the hand below the surface.', 'Bend the elbow slightly.', 'Scull small until pressure is felt.', 'Reset without letting the hips drop.'],
    common_mistakes: 'Straight-arm pressing|Hand too shallow|Chin tucking toward the chest',
    progression: 'Scull for six beats, then add one backstroke pull.',
    difficulty: 'Intermediate',
  }),
  drill({
    id: 'bk-rotation-timing',
    title: 'Backstroke Rotation Timing Drill',
    stroke: 'Backstroke',
    phase: 'Rotation',
    pack_ids: ['backstroke-hip-position'],
    fault_tags: 'late rotation, flat shoulders, over rotation, crossover entry, backstroke',
    purpose: 'Times shoulder rotation with hand entry so the arm does not cross the midline.',
    report_summary: 'Connects backstroke rotation to cleaner hand entry and catch setup.',
    coaching_cue: 'Shoulder opens, hand enters on its track.',
    setup: 'Use single-arm or 3-stroke backstroke at controlled speed.',
    execution_steps: ['Rotate the shoulder before entry.', 'Enter with the hand outside the head line.', 'Let the hip follow the shoulder.', 'Keep the kick compact.'],
    common_mistakes: 'Entering across the head|Rotating after the hand enters|Holding the breath',
    progression: 'Use the same timing in full backstroke over 25m.',
    difficulty: 'Intermediate',
  }),
  drill({
    id: 'bk-streamline-back-kick',
    title: 'Streamline Back Kick',
    stroke: 'Backstroke',
    phase: 'Body Line',
    pack_ids: ['backstroke-hip-position', 'streamline-starts-turns'],
    fault_tags: 'hips dropping, moving head, weak kick rhythm, body line, backstroke',
    purpose: 'Locks the body line while the swimmer maintains a compact backstroke kick.',
    report_summary: 'Reinforces high hips, quiet head position, and a steady kick rhythm.',
    coaching_cue: 'Ears squeezed, hips high, small fast kick.',
    setup: 'Push off on the back in tight streamline.',
    execution_steps: ['Lock the streamline before push-off.', 'Keep eyes up and head still.', 'Kick small under the surface.', 'Hold the line until speed fades.'],
    common_mistakes: 'Knees breaking the surface|Ribs flaring|Hands separating overhead',
    progression: 'Add breakout into full backstroke while keeping the same line.',
    difficulty: 'Beginner',
  }),
  drill({
    id: 'fly-body-dolphin',
    title: 'Body Dolphin',
    stroke: 'Butterfly',
    phase: 'Body Line',
    pack_ids: ['butterfly-rhythm-body-wave', 'streamline-starts-turns'],
    fault_tags: 'body wave, dolphin kick, butterfly rhythm',
    purpose: 'Builds a wave from chest to hips without arm timing.',
    coaching_cue: 'Chest presses, hips answer.',
    setup: 'Arms by side or in streamline with fins if needed.',
    execution_steps: ['Press the chest slightly.', 'Let hips rise as the wave travels.', 'Kick from the hips.', 'Keep the head low.'],
    common_mistakes: 'Kicking only from knees|Diving too deep|Lifting the head',
    progression: 'Add one-arm butterfly after body dolphin repeats.',
    equipment: 'fins optional',
  }),
  drill({
    id: 'fly-single-arm-rhythm',
    title: 'Single-Arm Butterfly Rhythm',
    stroke: 'Butterfly',
    phase: 'Timing',
    pack_ids: ['butterfly-rhythm-body-wave'],
    fault_tags: 'butterfly timing, second kick, breathing',
    purpose: 'Simplifies butterfly timing while keeping the two-kick rhythm.',
    coaching_cue: 'Kick in, kick out.',
    setup: 'One arm strokes while the other stays forward or by side.',
    execution_steps: ['Kick as the hand enters.', 'Press through the pull.', 'Kick as the hand exits.', 'Breathe low when needed.'],
    common_mistakes: 'Missing the second kick|Breathing too high|Straight-arm muscling',
    progression: 'Alternate single-arm and full butterfly by 12.5m.',
    difficulty: 'Intermediate',
    equipment: 'fins recommended',
  }),
  drill({
    id: 'fly-3-3-3',
    title: '3-3-3 Butterfly',
    stroke: 'Butterfly',
    phase: 'Timing',
    pack_ids: ['butterfly-rhythm-body-wave'],
    fault_tags: 'butterfly rhythm, body wave, timing',
    purpose: 'Transfers single-arm rhythm into full-stroke butterfly.',
    coaching_cue: 'Same rhythm, different arm pattern.',
    setup: 'Swim three right-arm, three left-arm, three full strokes.',
    execution_steps: ['Complete three right-arm strokes.', 'Complete three left-arm strokes.', 'Complete three full strokes.', 'Keep the two-kick rhythm consistent.'],
    common_mistakes: 'Changing tempo on full stroke|High breath|Flat body line',
    progression: 'Use 2-2-2, then full butterfly.',
    equipment: 'fins optional',
  }),
  drill({
    id: 'fly-low-breath',
    title: 'Low Breath Butterfly',
    stroke: 'Butterfly',
    phase: 'Breathing',
    pack_ids: ['butterfly-rhythm-body-wave'],
    fault_tags: 'high breath, butterfly timing, dropped hips',
    purpose: 'Keeps the breath low so the rhythm and hips do not collapse.',
    coaching_cue: 'Breathe forward, not up.',
    setup: 'Use short repeats with plenty of rest.',
    execution_steps: ['Start with body wave rhythm.', 'Let the breath skim forward.', 'Return the face before hand entry.', 'Keep the second kick connected.'],
    common_mistakes: 'Looking forward too long|Late face return|Forcing the arms over water',
    progression: 'Add one extra full-stroke cycle while holding the low breath.',
    difficulty: 'Advanced',
  }),
  drill({
    id: 'fly-kick-pull-kick-timing',
    title: 'Kick-Pull-Kick Timing Drill',
    stroke: 'Butterfly',
    phase: 'Timing',
    pack_ids: ['butterfly-rhythm-body-wave'],
    fault_tags: 'weak second kick, late second kick, rushed rhythm, butterfly timing',
    purpose: 'Clarifies the two-kick butterfly rhythm: first kick supports entry, second kick supports the finish and recovery.',
    report_summary: 'Rebuilds butterfly around a clear first-kick and second-kick rhythm.',
    coaching_cue: 'Kick in, pull through, kick out.',
    setup: 'Use short repeats with fins if needed.',
    execution_steps: ['Kick as the hands enter.', 'Start the pull after the body wave sets.', 'Kick again as the hands finish.', 'Recover low and relaxed.'],
    common_mistakes: 'Missing the second kick|Pulling before the body line sets|Breathing too high',
    progression: 'Move from drill rhythm to 3-3-3 butterfly.',
    difficulty: 'Intermediate',
    equipment: 'fins optional',
  }),
  drill({
    id: 'fly-side-dolphin-kick',
    title: 'Butterfly Kick on Side',
    stroke: 'Butterfly',
    phase: 'Body Line',
    pack_ids: ['butterfly-rhythm-body-wave'],
    fault_tags: 'flat body wave, low hips, weak dolphin kick, butterfly',
    purpose: 'Teaches dolphin rhythm through the whole body without the arms hiding timing faults.',
    report_summary: 'Helps the swimmer feel body wave and kick timing without forcing full butterfly.',
    coaching_cue: 'Press through the ribs, let the hips answer.',
    setup: 'Kick on one side with the lower arm extended and fins if useful.',
    execution_steps: ['Hold a long side line.', 'Let the chest initiate the wave.', 'Kick from the hips, not the knees.', 'Switch sides before rhythm breaks down.'],
    common_mistakes: 'Kicking only from the knees|Rolling onto the back|Holding the head too high',
    progression: 'Alternate side dolphin with body dolphin, then single-arm butterfly.',
    difficulty: 'Intermediate',
    equipment: 'fins optional',
  }),
  drill({
    id: 'st-wall-streamline-lock',
    title: 'Wall Streamline Lock',
    stroke: 'General',
    phase: 'Underwater',
    pack_ids: ['streamline-starts-turns'],
    fault_tags: 'streamline, push-off, underwater, starts and turns',
    purpose: 'Builds a tight line before adding kick or breakout timing.',
    coaching_cue: 'Lock hands, squeeze ears, ribs quiet.',
    setup: 'Push off from the wall in streamline.',
    execution_steps: ['Set hands locked before push.', 'Squeeze ears with upper arms.', 'Push off and hold line.', 'Stop before the line loosens.'],
    common_mistakes: 'Hands separating|Head lifted|Fluttering legs immediately',
    progression: 'Add three dolphin kicks before breakout.',
    difficulty: 'Beginner',
  }),
  drill({
    id: 'st-dolphin-count',
    title: 'Dolphin Kick Count Breakout',
    stroke: 'General',
    phase: 'Breakout',
    pack_ids: ['streamline-starts-turns'],
    fault_tags: 'breakout, underwater, dolphin kick, streamline',
    purpose: 'Finds the best number of underwater kicks before speed drops.',
    coaching_cue: 'Break out before the line slows.',
    setup: 'Use push-offs with coach timing or visual feedback.',
    execution_steps: ['Push off in tight streamline.', 'Take a set number of dolphin kicks.', 'Break out with speed.', 'Compare speed across different counts.'],
    common_mistakes: 'Staying under too long|Breaking out upward|Loose arms during kicks',
    progression: 'Use the chosen count in race-specific turns.',
    equipment: 'none',
  }),
  drill({
    id: 'st-turn-push-line',
    title: 'Turn Push-Off Line',
    stroke: 'General',
    phase: 'Turn',
    pack_ids: ['streamline-starts-turns'],
    fault_tags: 'turn, push-off, streamline, wall speed',
    purpose: 'Improves the line leaving the wall after a turn.',
    coaching_cue: 'Feet plant, body locks, then push.',
    setup: 'Start close to the wall and perform repeated push-offs.',
    execution_steps: ['Plant feet firmly on the wall.', 'Set streamline before pushing.', 'Push straight through the body line.', 'Hold until speed fades.'],
    common_mistakes: 'Pushing before arms lock|Angled push-off|Looking forward',
    progression: 'Add the turn approach before the push-off.',
    difficulty: 'Beginner',
  }),
  drill({
    id: 'st-first-stroke-timing',
    title: 'First Stroke Breakout Timing',
    stroke: 'General',
    phase: 'Breakout',
    pack_ids: ['streamline-starts-turns'],
    fault_tags: 'breakout timing, first stroke, starts and turns',
    purpose: 'Connects underwater speed to a clean first stroke without popping up.',
    coaching_cue: 'First stroke catches while speed is still there.',
    setup: 'Push off, kick underwater, and take one breakout stroke.',
    execution_steps: ['Leave the wall tight.', 'Hold the chosen kick count.', 'Start the first stroke before surfacing fully.', 'Keep the head low through breakout.'],
    common_mistakes: 'Breathing on the first stroke|Starting the pull too late|Breaking streamline early',
    progression: 'Add two to four full strokes after breakout.',
    difficulty: 'Intermediate',
  }),
  drill({
    id: 'start-set-position-balance',
    title: 'Stable Set Position Rehearsal',
    stroke: 'Starts',
    phase: 'Set Position',
    pack_ids: ['streamline-starts-turns'],
    fault_tags: 'unstable set position, rearward balance, start setup',
    purpose: 'Builds a repeatable set position that the coach can check before reaction work.',
    coaching_cue: 'Still hips, loaded legs, eyes quiet.',
    setup: 'Use a dry block or poolside rehearsal with a coach controlling the start command.',
    execution_steps: ['Place feet in the chosen stance.', 'Shift pressure through the feet without rocking.', 'Hold a still set position for two seconds.', 'Reset and repeat with the same hand and hip position.'],
    common_mistakes: 'Rocking after set|Hips too low|Weight entirely on the rear foot',
    progression: 'Add a controlled step or jump into a safe landing zone.',
    duration_or_reps: '4–6 controlled rehearsals',
    difficulty: 'Beginner',
    when_to_use: 'Use when start position changes between repetitions or the swimmer loses balance before the signal.',
    safety_notes: 'Use supervised block practice and confirm the landing area is clear.',
  }),
  drill({
    id: 'start-reaction-entry-line',
    title: 'Reaction to Entry Line',
    stroke: 'Starts',
    phase: 'Reaction and Entry',
    pack_ids: ['streamline-starts-turns'],
    fault_tags: 'slow reaction, short entry, loose entry line',
    purpose: 'Connects the start signal to a committed forward entry without sacrificing the body line.',
    coaching_cue: 'React, drive forward, make one clean hole.',
    setup: 'Use a clear lane with coach-controlled signals and full recovery between repetitions.',
    execution_steps: ['Hold the chosen set position.', 'React to the signal without an early movement.', 'Drive arms and hips forward together.', 'Enter through a narrow line and hold streamline.'],
    common_mistakes: 'Jumping upward instead of forward|Hands separating|Lifting the head before entry',
    progression: 'Add timed 10 m starts only after entry shape is repeatable.',
    duration_or_reps: '4 starts with full recovery',
    difficulty: 'Competitive',
    when_to_use: 'Use when the reaction and entry look disconnected or the swimmer loses line before water entry.',
    safety_notes: 'Qualified coach supervision is required for block starts.',
  }),
  drill({
    id: 'start-streamline-entry-hold',
    title: 'Start Streamline Hold',
    stroke: 'Starts',
    phase: 'Streamline',
    pack_ids: ['streamline-starts-turns'],
    fault_tags: 'broken streamline, loose hands, head lift after entry',
    purpose: 'Reinforces a locked line immediately after entry before underwater movement begins.',
    coaching_cue: 'Enter, lock, then move.',
    setup: 'Start from the side or block according to swimmer experience and coaching policy.',
    execution_steps: ['Enter through a narrow hand line.', 'Lock hands and squeeze the head between the arms.', 'Hold the shape briefly after entry.', 'Begin the permitted underwater action without breaking line.'],
    common_mistakes: 'Kicking before streamline is set|Looking forward|Hands opening on entry',
    progression: 'Add the planned kick count and breakout timing.',
    duration_or_reps: '4 x entry plus streamline',
    difficulty: 'Competitive',
    when_to_use: 'Use when the swimmer creates a good entry but loses shape before the underwater phase.',
  }),
  drill({
    id: 'start-underwater-breakout-build',
    title: 'Start Breakout Build',
    stroke: 'Starts',
    phase: 'Underwater Breakout',
    pack_ids: ['streamline-starts-turns'],
    fault_tags: 'early breakout, late breakout, first stroke timing',
    purpose: 'Helps the coach compare breakout choices while keeping the first stroke connected to entry speed.',
    coaching_cue: 'Hold speed, then surface into the stroke.',
    setup: 'Mark 10 m and use the same start effort for each repetition.',
    execution_steps: ['Complete a controlled start and streamline.', 'Use the planned underwater action.', 'Begin the first stroke before speed visibly fades.', 'Compare distance and rhythm with the coach.'],
    common_mistakes: 'Breathing on the first stroke|Staying underwater after speed fades|Breaking upward',
    progression: 'Add race-tempo strokes to 15 m.',
    duration_or_reps: '4 x 10–15 m with full recovery',
    difficulty: 'Advanced',
    when_to_use: 'Use when the swimmer loses start speed during the transition into surface swimming.',
  }),
  drill({
    id: 'turn-approach-count',
    title: 'Turn Approach Count',
    stroke: 'Turns',
    phase: 'Approach',
    pack_ids: ['streamline-starts-turns'],
    fault_tags: 'inconsistent approach, gliding into wall, short final stroke',
    purpose: 'Creates a repeatable final-stroke pattern so the swimmer arrives at the wall with speed.',
    coaching_cue: 'Carry speed in; no extra glide.',
    setup: 'Start 7–10 m from the wall and identify a consistent visual cue.',
    execution_steps: ['Swim toward the wall at controlled speed.', 'Count the final strokes from the visual cue.', 'Keep rhythm through the last stroke.', 'Record the count that produces a comfortable wall distance.'],
    common_mistakes: 'Looking up early|Adding a glide|Changing stroke length at the flags',
    progression: 'Repeat at race tempo while keeping the same decision point.',
    duration_or_reps: '6 approaches with easy return',
    difficulty: 'Beginner',
    when_to_use: 'Use when wall distance changes between turns or the swimmer slows before rotation.',
  }),
  drill({
    id: 'turn-rotation-compact',
    title: 'Compact Rotation Rehearsal',
    stroke: 'Turns',
    phase: 'Rotation',
    pack_ids: ['streamline-starts-turns'],
    fault_tags: 'slow rotation, wide tuck, turn timing',
    purpose: 'Builds a compact, controlled rotation without asking the swimmer to rush the wall contact.',
    coaching_cue: 'Fast tuck, quiet head, feet find the wall.',
    setup: 'Begin close to the wall at low speed with clear lane space.',
    execution_steps: ['Approach with one controlled stroke.', 'Tuck through a compact rotation.', 'Bring feet to the wall without searching.', 'Pause before push-off to check placement.'],
    common_mistakes: 'Throwing the head back|Opening the tuck|Feet landing too wide',
    progression: 'Remove the pause and connect to push-off.',
    duration_or_reps: '6 turn rotations',
    difficulty: 'Intermediate',
    when_to_use: 'Use when rotation is slow or the feet land inconsistently.',
  }),
  drill({
    id: 'turn-wall-contact-check',
    title: 'Wall Contact Check',
    stroke: 'Turns',
    phase: 'Wall Contact',
    pack_ids: ['streamline-starts-turns'],
    fault_tags: 'poor foot placement, wide feet, weak wall contact',
    purpose: 'Gives the coach a repeatable checkpoint for foot position before the push-off.',
    coaching_cue: 'Feet firm, hips close, line ready.',
    setup: 'Use low-speed turns and pause briefly when the feet contact the wall.',
    execution_steps: ['Rotate into the wall.', 'Place both feet firmly at a comfortable width.', 'Check hip distance and knee position.', 'Set the upper body before pushing away.'],
    common_mistakes: 'Feet too high or low|Hips drifting away|Pushing before the arms set',
    progression: 'Shorten the pause until contact and push become continuous.',
    duration_or_reps: '4–6 paused wall contacts',
    difficulty: 'Beginner',
    when_to_use: 'Use when push-off direction changes or the swimmer slips on contact.',
  }),
  drill({
    id: 'turn-push-off-direction',
    title: 'Straight Push-Off Direction',
    stroke: 'Turns',
    phase: 'Push-off',
    pack_ids: ['streamline-starts-turns'],
    fault_tags: 'angled push-off, weak push, broken streamline',
    purpose: 'Connects firm wall contact to a straight, coach-observed exit line.',
    coaching_cue: 'Set the line, push through it.',
    setup: 'Use lane-line or pool-floor references to judge direction.',
    execution_steps: ['Plant the feet after rotation.', 'Set hands and head in streamline.', 'Push through both legs together.', 'Hold a straight path before adding kick.'],
    common_mistakes: 'Twisting during push|Arms setting late|Pushing toward the surface',
    progression: 'Add the planned underwater action and breakout.',
    duration_or_reps: '6 push-offs with easy recovery',
    difficulty: 'Intermediate',
    when_to_use: 'Use when the swimmer leaves the wall sideways, upward, or without a stable line.',
  }),
  drill({
    id: 'turn-streamline-breakout',
    title: 'Turn Streamline to Breakout',
    stroke: 'Turns',
    phase: 'Streamline / Breakout',
    pack_ids: ['streamline-starts-turns'],
    fault_tags: 'loose streamline, early breakout, late first stroke',
    purpose: 'Links the push-off line to a controlled first stroke without losing wall speed.',
    coaching_cue: 'Stay narrow, surface into speed.',
    setup: 'Push from the wall and finish 10–15 m beyond it.',
    execution_steps: ['Leave the wall in locked streamline.', 'Use the planned underwater action.', 'Begin breakout before momentum fades.', 'Keep the first stroke long and connected.'],
    common_mistakes: 'Opening arms early|Looking forward|Breathing immediately',
    progression: 'Add race-tempo swimming after the breakout.',
    duration_or_reps: '6 x 10–15 m',
    difficulty: 'Competitive',
    when_to_use: 'Use when the turn is quick but the swimmer loses speed between push-off and first stroke.',
  }),
  drill({
    id: 'general-body-line-check',
    title: 'Coach Body-Line Check',
    stroke: 'General',
    phase: 'Body Line',
    pack_ids: [],
    fault_tags: 'body line, head position, hip alignment, posture',
    purpose: 'Gives the coach a simple repeatable body-line checkpoint before adding stroke-specific changes.',
    coaching_cue: 'Long through the head, ribs, hips, and heels.',
    setup: 'Use an easy push-off or low-speed swim with a clear side view.',
    execution_steps: ['Pause or slow the review at a stable moment.', 'Check head, rib, hip, and ankle alignment.', 'Add one coach-drawn reference line if useful.', 'Choose one cue rather than correcting every difference at once.'],
    common_mistakes: 'Changing several cues at once|Treating a single frame as the whole stroke|Using the line as an exact measurement',
    progression: 'Repeat the check during the swimmer’s primary stroke and compare the same phase.',
    duration_or_reps: '3–4 short repeats or review moments',
    difficulty: 'Beginner',
    when_to_use: 'Use when posture or alignment is the main coaching priority across any stroke.',
  }),
  // ── Phase B: additional general coach drills across under-filled strokes/phases ──
  drill({
    id: 'fly-single-arm',
    title: 'Single-Arm Butterfly',
    stroke: 'Butterfly',
    phase: 'Catch',
    pack_ids: [],
    fault_tags: 'dropped elbow, weak catch, poor timing, butterfly',
    purpose: 'Isolates one arm so the swimmer can build a strong catch and steady two-kick timing without full-stroke fatigue.',
    coaching_cue: 'One arm leads, two kicks anchor.',
    setup: 'One arm strokes butterfly, the other stays extended in front; breathe to the front and swap arms each length.',
    execution_steps: ['Extend both arms and set a flat body line.', 'Pull one arm through with a high elbow.', 'Keep the small kick on entry and the strong kick on hand exit.', 'Recover over the water and swap arms next length.'],
    common_mistakes: 'Pulling with a dropped elbow|Lifting the head too early|Losing the two-kick rhythm',
    progression: 'Alternate arms every three strokes, then join to full stroke.',
    regression: 'Use fins to hold rhythm and reduce fatigue.',
    difficulty: 'Intermediate',
    equipment: 'fins optional',
    duration_or_reps: '8 x 25m, swap arms each length',
  }),
  drill({
    id: 'fly-2-kick-timing',
    title: 'Two-Kick Timing Fly',
    stroke: 'Butterfly',
    phase: 'Timing',
    pack_ids: [],
    fault_tags: 'late second kick, kick timing, sinking hips, butterfly',
    purpose: 'Locks the small kick on hand entry and the strong kick on hand exit.',
    coaching_cue: 'Kick in, kick out.',
    setup: 'Full-stroke butterfly at easy to moderate effort, counting the two kicks per cycle.',
    execution_steps: ['Enter the hands and add the first small kick.', 'Catch and pull through.', 'Add the strong second kick as the hands leave the water.', 'Recover and repeat with the same timing.'],
    common_mistakes: 'Missing the first kick|Kicking both beats the same size|Dropping the hips between cycles',
    progression: 'Hold the timing over longer swims and race pace.',
    regression: 'Return to single-arm butterfly to rebuild rhythm.',
    difficulty: 'Advanced',
    equipment: 'none',
    duration_or_reps: '8 x 25m with rest, focus on timing',
  }),
  drill({
    id: 'st-streamline-jump',
    title: 'Vertical Streamline Jump',
    stroke: 'Starts',
    phase: 'Set Position',
    pack_ids: [],
    fault_tags: 'loose streamline, weak line off blocks, starts',
    purpose: 'Builds a tight, overlapped streamline shape that carries speed off the start.',
    coaching_cue: 'Squeeze the ears, one line.',
    setup: 'On the pool deck, jump vertically into a locked streamline and land softly.',
    execution_steps: ['Stand tall and lock the hands into a streamline.', 'Squeeze the arms behind the ears.', 'Jump up holding the shape.', 'Land softly with the line still held.'],
    common_mistakes: 'Arms behind the head|Gap between the hands|Losing the line on landing',
    progression: 'Transfer the same shape to a push-off streamline in the water.',
    regression: 'Hold the streamline statically against a wall first.',
    difficulty: 'Beginner',
    equipment: 'none',
    duration_or_reps: '8-10 controlled reps on deck',
    safety_notes: 'Dryland drill — use a dry, non-slip surface with clear space and land softly.',
  }),
  drill({
    id: 'st-dive-entry-hole',
    title: 'Clean Entry Hole Dive',
    stroke: 'Starts',
    phase: 'Reaction and Entry',
    pack_ids: [],
    fault_tags: 'flat entry, belly flop, deep entry, starts',
    purpose: 'Trains a clean streamlined entry through a single point with the hands leading.',
    coaching_cue: 'Hands make the hole, body follows.',
    setup: 'From a legal dive position, dive and aim to enter through one point with a locked streamline.',
    execution_steps: ['Set a balanced start position.', 'Drive out over the water into streamline.', 'Point the hands at the entry spot.', 'Follow the hands through the same point and hold the line.'],
    common_mistakes: 'Flat slapping entry|Head lifting on entry|Streamline opening under water',
    progression: 'Add a set dolphin-kick count after entry.',
    regression: 'Start from the edge in a crouch before using blocks.',
    difficulty: 'Intermediate',
    equipment: 'none',
    duration_or_reps: '6-8 dives with full rest',
    safety_notes: 'Dive only into confirmed safe water depth per facility rules, with coach supervision.',
  }),
  drill({
    id: 'st-underwater-count',
    title: 'Start Underwater Kick Count',
    stroke: 'Starts',
    phase: 'Underwater Breakout',
    pack_ids: [],
    fault_tags: 'early breakout, short underwater, breakout timing, starts',
    purpose: 'Builds a consistent underwater dolphin-kick count off the start before breakout.',
    coaching_cue: 'Hold the line, kick to the mark.',
    setup: 'From a legal start or push, hold streamline and count kicks to a fixed pool marker.',
    execution_steps: ['Enter or push into a tight streamline.', 'Hold the line under the surface.', 'Add a set number of dolphin kicks, e.g. three to five.', 'Break out at the marker, not before.'],
    common_mistakes: 'Breaking out early|Streamline opening under water|Kicking from the knees',
    progression: 'Increase the kick count or add a first-stroke breakout.',
    regression: 'Reduce the count and use fins to feel the rhythm.',
    difficulty: 'Intermediate',
    equipment: 'fins optional',
    duration_or_reps: '6 x 15m from push, controlled',
    safety_notes: 'Supervised; confirm safe depth and avoid prolonged breath-holding.',
  }),
  drill({
    id: 'st-reaction-response',
    title: 'Reaction Start Response',
    stroke: 'Starts',
    phase: 'Reaction and Entry',
    pack_ids: [],
    fault_tags: 'slow reaction, late block exit, starts',
    purpose: 'Sharpens the response from set position to first movement off the start.',
    coaching_cue: 'React, don’t think.',
    setup: 'From a held set position, leave on a sharp signal and focus on a fast, clean exit.',
    execution_steps: ['Take a balanced, still set position.', 'Wait for the signal without pre-moving.', 'Drive out fast into streamline on the signal.', 'Reset and repeat with full recovery.'],
    common_mistakes: 'Pre-moving before the signal|Rushing and losing the line|Flat entry from hurrying',
    progression: 'Add entry and underwater kicks to a full start.',
    regression: 'Practise the response standing on the deck first.',
    difficulty: 'Advanced',
    equipment: 'none',
    duration_or_reps: '6-8 reps, full rest between',
    safety_notes: 'Supervised; dive only into confirmed safe depth and use a consistent start signal.',
  }),
  drill({
    id: 'tn-approach-sight',
    title: 'Turn Approach Sighting',
    stroke: 'Turns',
    phase: 'Approach',
    pack_ids: [],
    fault_tags: 'gliding into the wall, mistimed turn, turns',
    purpose: 'Helps swimmers judge the flags-to-wall distance and keep speed into the turn.',
    coaching_cue: 'Accelerate to the wall, don’t glide.',
    setup: 'Swim into the wall using a consistent stroke count from a fixed marker or the flags.',
    execution_steps: ['Note your position at the flags or a fixed marker.', 'Hold stroke speed into the wall.', 'Keep the eyes down on the freestyle approach.', 'Start the turn without a long glide.'],
    common_mistakes: 'Long glide into the wall|Lifting the head to look|Changing stroke count each time',
    progression: 'Add the full turn and push-off to streamline.',
    regression: 'Walk through the approach at slow speed first.',
    difficulty: 'Beginner',
    equipment: 'none',
    duration_or_reps: '6-8 approaches into the wall',
    safety_notes: 'Know your distance to the wall and keep controlled speed on approach.',
  }),
  drill({
    id: 'tn-fast-feet',
    title: 'Fast-Feet Wall Contact',
    stroke: 'Turns',
    phase: 'Wall Contact',
    pack_ids: [],
    fault_tags: 'slow foot plant, weak push, feet too high, turns',
    purpose: 'Speeds up the foot plant and the change of direction on the wall.',
    coaching_cue: 'Feet down, feet gone.',
    setup: 'From a short approach, rotate and plant the feet quickly, then push straight into streamline.',
    execution_steps: ['Approach and start the rotation early.', 'Plant both feet quickly at push-off height.', 'Push straight into a tight streamline.', 'Add a few underwater kicks before breakout.'],
    common_mistakes: 'Feet planted too high|Pausing on the wall|Loose streamline off the push',
    progression: 'Time the turn from the last stroke to breakout.',
    regression: 'Practise the wall plant slowly from a float.',
    difficulty: 'Intermediate',
    equipment: 'none',
    duration_or_reps: '6-8 turns from a short approach',
    safety_notes: 'Judge the wall distance carefully; supervised practice.',
  }),
  drill({
    id: 'tn-pushoff-line',
    title: 'Push-Off Line Hold',
    stroke: 'Turns',
    phase: 'Push-off',
    pack_ids: [],
    fault_tags: 'loose streamline off wall, early breakout, turns',
    purpose: 'Builds a tight, fast streamline off every wall.',
    coaching_cue: 'Push into one straight line.',
    setup: 'Push off the wall on the front or back into a locked streamline and hold speed before breakout.',
    execution_steps: ['Set the feet on the wall.', 'Push into an overlapped streamline.', 'Hold the line and let the speed carry.', 'Break out cleanly at the right distance.'],
    common_mistakes: 'Arms apart in streamline|Breaking out too early|Head out of line',
    progression: 'Add dolphin kicks and a first-stroke breakout.',
    regression: 'Hold a static streamline against the wall first.',
    difficulty: 'Intermediate',
    equipment: 'none',
    duration_or_reps: '8 push-offs, alternate front and back',
    safety_notes: 'Confirm a clear lane ahead before each push-off.',
  }),
  drill({
    id: 'tn-back-cross',
    title: 'Backstroke-to-Free Cross Turn',
    stroke: 'Turns',
    phase: 'Rotation',
    pack_ids: [],
    fault_tags: 'over-rotation, mistimed backstroke turn, turns',
    purpose: 'Times the single stroke to the front and the flip on backstroke turns.',
    coaching_cue: 'One stroke, roll, flip.',
    setup: 'Approach on backstroke, take one stroke onto the front, then flip and push off on the back.',
    execution_steps: ['Track the distance from the backstroke flags.', 'Roll onto the front with a single stroke.', 'Flip quickly and plant the feet.', 'Push off on the back into streamline.'],
    common_mistakes: 'More than one stroke onto the front|Losing the wall distance|Pushing off flat',
    progression: 'Add underwater dolphin kicks to breakout.',
    regression: 'Rehearse the roll and flip slowly away from the wall.',
    difficulty: 'Advanced',
    equipment: 'none',
    duration_or_reps: '6-8 turns with rest',
    safety_notes: 'Know the wall distance from the flags; supervised to avoid head contact with the wall.',
  }),
  drill({
    id: 'gen-streamline-kick',
    title: 'Streamline Kick Balance',
    stroke: 'General',
    phase: 'Body Line',
    pack_ids: [],
    fault_tags: 'sinking hips, loose streamline, head position',
    purpose: 'Builds a stable, long body line on the surface that transfers to every stroke.',
    coaching_cue: 'Long, quiet, high hips.',
    setup: 'Streamline kick on the front with the face down, stopping to breathe rather than lifting the head.',
    execution_steps: ['Push into a tight streamline.', 'Keep the head in line, eyes down.', 'Kick steadily to hold the hips high.', 'Stop to breathe instead of lifting the head while kicking.'],
    common_mistakes: 'Head lifting to breathe|Hips dropping|Streamline opening',
    progression: 'Add gentle rotation to each side.',
    regression: 'Use fins or hold a board in streamline.',
    difficulty: 'Beginner',
    equipment: 'fins optional',
    duration_or_reps: '6 x 25m steady',
  }),
  drill({
    id: 'gen-hollow-hold',
    title: 'Hollow-Body Float Hold',
    stroke: 'General',
    phase: 'Body Line',
    pack_ids: [],
    fault_tags: 'core collapse, sagging hips, arched back',
    purpose: 'Develops the core hold that keeps the body line long and connected.',
    coaching_cue: 'Belt tight, ribs down.',
    setup: 'Float face-down in a streamline and hold a firm, connected core for short counts, breathing between holds.',
    execution_steps: ['Push into a streamline float.', 'Gently brace the core so the hips stay up.', 'Hold for a short count.', 'Relax, breathe, and repeat.'],
    common_mistakes: 'Arching the lower back|Holding the breath too long|Tensing the shoulders',
    progression: 'Add a slow kick while holding the core.',
    regression: 'Practise the brace standing or against the wall.',
    difficulty: 'Beginner',
    equipment: 'none',
    duration_or_reps: '6-8 short holds with easy breathing',
  }),
  drill({
    id: 'gen-6-kick-switch',
    title: '6-Kick Switch Balance',
    stroke: 'General',
    phase: 'Rotation',
    pack_ids: [],
    fault_tags: 'flat body, weak rotation, unstable lead arm',
    purpose: 'Builds a stable side-lying balance and controlled rotation used in freestyle and backstroke.',
    coaching_cue: 'Balance on the side, then switch.',
    setup: 'Kick six beats on one side with the lead arm extended, then switch to the other side.',
    execution_steps: ['Extend one arm and rotate onto that side.', 'Kick six steady beats holding balance.', 'Switch with one stroke to the other side.', 'Keep the head still and low throughout.'],
    common_mistakes: 'Rolling flat on the back|Lead arm sinking|Head lifting on the switch',
    progression: 'Reduce to three kicks per side, then full swim.',
    regression: 'Use fins for balance and a snorkel to steady the head.',
    difficulty: 'Intermediate',
    equipment: 'fins optional',
    duration_or_reps: '6 x 50m alternating sides',
  }),
  drill({
    id: 'gen-vertical-kick',
    title: 'Vertical Kick Posture',
    stroke: 'General',
    phase: 'Kick Drive',
    pack_ids: [],
    fault_tags: 'weak kick, poor posture, bent knees',
    purpose: 'Builds kick strength and a tall, connected posture in deep water.',
    coaching_cue: 'Tall spine, kick from the hips.',
    setup: 'In deep water, kick vertically to keep the head up, arms crossed or held at the surface.',
    execution_steps: ['Hold a tall posture in deep water.', 'Kick steadily from the hips, not the knees.', 'Keep the chin at the surface.', 'Rest on the wall or lane rope between efforts.'],
    common_mistakes: 'Kicking from the knees|Leaning back|Holding the breath',
    progression: 'Add short arms-up intervals to raise the demand.',
    regression: 'Hold the wall or a lane rope and reduce the time.',
    difficulty: 'Advanced',
    equipment: 'none',
    duration_or_reps: '6-8 x 15-20 seconds with rest',
    safety_notes: 'Deep-water competency required; supervised, with a wall or lane rope within reach.',
  }),
  drill({
    id: 'bk-single-arm',
    title: 'Single-Arm Backstroke',
    stroke: 'Backstroke',
    phase: 'Catch',
    pack_ids: [],
    fault_tags: 'dropped elbow catch, over-reach, crossover entry, backstroke',
    purpose: 'Isolates the catch and entry line so the swimmer can feel a clean, connected pull.',
    coaching_cue: 'Pinky in, press to the hip.',
    setup: 'One arm swims backstroke, the other rests at the side; swap arms each length.',
    execution_steps: ['Enter little finger first at shoulder width.', 'Set an early catch with the forearm.', 'Press the water to the hip.', 'Keep the body line stable and swap arms next length.'],
    common_mistakes: 'Entering across the midline|Pulling with a flat hand|Rolling too far',
    progression: 'Alternate arms every three strokes, then full stroke.',
    regression: 'Use fins to steady the body while learning the catch.',
    difficulty: 'Intermediate',
    equipment: 'none',
    duration_or_reps: '8 x 25m, swap arms each length',
  }),
  drill({
    id: 'bk-double-arm',
    title: 'Double-Arm Backstroke',
    stroke: 'Backstroke',
    phase: 'Pull',
    pack_ids: [],
    fault_tags: 'weak finish, no hip drive, timing, backstroke',
    purpose: 'Builds symmetrical power and connects the pull to the hips.',
    coaching_cue: 'Drive both hips, finish past the hips.',
    setup: 'Both arms pull together in backstroke, entering and finishing at the same time.',
    execution_steps: ['Enter both arms together at shoulder width.', 'Catch and pull both arms down together.', 'Drive the hips as the arms finish past the hips.', 'Recover both arms together and reset the line.'],
    common_mistakes: 'Short finish at the hips|No hip involvement|Losing balance without rotation',
    progression: 'Alternate double-arm and normal backstroke by length.',
    regression: 'Use fins to keep the hips up while learning the timing.',
    difficulty: 'Advanced',
    equipment: 'fins optional',
    duration_or_reps: '6 x 25m controlled',
  }),
  drill({
    id: 'fr-tempo-neg',
    title: 'Tempo Negative-Split Swim',
    stroke: 'Freestyle',
    phase: 'Timing',
    pack_ids: [],
    fault_tags: 'rushed tempo, uneven pacing, dropping stroke length, freestyle',
    purpose: 'Holds stroke length while raising tempo through the back half of a swim.',
    coaching_cue: 'Same length, faster turnover.',
    setup: 'Swim a controlled distance, keeping stroke count steady while increasing tempo in the second half.',
    execution_steps: ['Swim the first half at a steady, long stroke.', 'Note the stroke count per length.', 'Raise the tempo in the second half.', 'Hold the same stroke count as the tempo rises.'],
    common_mistakes: 'Stroke count climbing with tempo|Rushing from the first length|Losing the catch under speed',
    progression: 'Use a tempo trainer to step the rate up in stages.',
    regression: 'Shorten the distance and hold a single steady tempo.',
    difficulty: 'Elite',
    equipment: 'tempo trainer optional',
    duration_or_reps: '4-6 x 100m negative split',
  }),
  drill({
    id: 'bs-2kick-1pull',
    title: 'Two-Kick One-Pull Breaststroke',
    stroke: 'Breaststroke',
    phase: 'Timing',
    pack_ids: [],
    fault_tags: 'rushed timing, no glide, sinking after pull, breaststroke',
    purpose: 'Exaggerates the glide and kick before adding pull frequency.',
    coaching_cue: 'Kick, kick, then pull.',
    setup: 'Swim breaststroke with two kicks for every one pull, holding a clear glide between.',
    execution_steps: ['Take one pull and shoot the hands forward.', 'Add a full kick and glide.', 'Add a second kick and glide.', 'Take the next pull once forward motion slows.'],
    common_mistakes: 'Pulling before the glide finishes|Lifting the head high|Weak second kick',
    progression: 'Return to one-kick one-pull with the same patient timing.',
    regression: 'Practise kick-only glide before adding the pull.',
    difficulty: 'Intermediate',
    equipment: 'none',
    duration_or_reps: '6 x 50m controlled',
  }),
  drill({
    id: 'bs-narrow-band',
    title: 'Narrow-Knee Band Kick',
    stroke: 'Breaststroke',
    phase: 'Kick Recovery',
    pack_ids: [],
    fault_tags: 'wide knees, kick finishes wide, breaststroke',
    purpose: 'Keeps the knees inside the hip line during the breaststroke kick recovery.',
    coaching_cue: 'Heels up, knees quiet.',
    setup: 'Place a light band around the thighs and kick breaststroke, holding the wall or a board.',
    execution_steps: ['Loop a light band around the thighs above the knees.', 'Recover the heels toward the seat.', 'Keep the knees inside the hips.', 'Turn the feet and snap together.'],
    common_mistakes: 'Knees dropping wide|Recovering the heels too slowly|Snapping before the feet turn',
    progression: 'Remove the band and hold the same narrow feel.',
    regression: 'Kick without the band at slow effort first.',
    difficulty: 'Intermediate',
    equipment: 'light band',
    duration_or_reps: '6 x 25m kick, band on',
    safety_notes: 'Use a light resistance band only; stop if the knees feel any strain.',
  }),
  drill({
    id: 'bs-race-pullout',
    title: 'Race Pull-Out Sequence',
    stroke: 'Breaststroke',
    phase: 'Underwater',
    pack_ids: [],
    fault_tags: 'slow pull-out, mistimed breakout, early surface, breaststroke',
    purpose: 'Sequences the pull-down, kick, and breakout to race standard off the wall.',
    coaching_cue: 'Pull, kick, breakout — one flow.',
    setup: 'From a push or start, complete one legal breaststroke pull-down with a single kick into breakout.',
    execution_steps: ['Push into a tight streamline.', 'Pull down to the thighs in one motion.', 'Add one breaststroke kick as the hands recover.', 'Break out into the first stroke without pausing.'],
    common_mistakes: 'Pausing between pull and kick|Surfacing too early|Losing streamline on recovery',
    progression: 'Add the pull-out to full-stroke swims off each wall.',
    regression: 'Break the sequence into pull-only and kick-only parts.',
    difficulty: 'Advanced',
    equipment: 'none',
    duration_or_reps: '6 from push, full rest',
    safety_notes: 'Supervised; confirm safe depth and avoid prolonged breath-holding.',
  }),
];

export function getDefaultDrills() {
  return DEFAULT_DRILLS.map((item) => ({ ...item }));
}

export function getDefaultDrillPacks() {
  return DEFAULT_DRILL_PACKS.map((item) => ({ ...item }));
}
