export const DEFAULT_DRILL_PACKS = [
  {
    id: 'breaststroke-kick-timing',
    title: 'Breaststroke Kick Timing',
    stroke: 'Breaststroke',
    phases: ['Kick Recovery', 'Kick Drive', 'Timing'],
    faults: ['Kick starts too early', 'Late foot snap', 'No glide after kick'],
    objective: 'Build the sequence from heel recovery to foot turn, snap, and short glide so the kick supports forward momentum.',
    primaryCue: 'Heels first, turn late, snap together.',
    cueTheme: 'Patient heel recovery before a fast snap.',
    bestFor: 'Swimmers who rush the kick or lose rhythm between pull, kick, and glide.',
    equipment: 'Wall, board, or fins optional',
    diffRange: 'Beginner - Intermediate',
    whenToUse: 'Use early in breaststroke technique sets before full-stroke timing work.',
    whenNotToUse: 'Hold off when knee width or foot position is the bigger limiter.',
    matchKeywords: ['breaststroke', 'kick timing', 'heel', 'snap', 'glide'],
  },
  {
    id: 'breaststroke-knee-width-control',
    title: 'Breaststroke Knee Width Control',
    stroke: 'Breaststroke',
    phases: ['Kick Recovery', 'Kick Drive'],
    faults: ['Wide knees', 'Knees drop under body', 'Kick finishes wide'],
    objective: 'Keep the recovery narrow and controlled so the swimmer holds a cleaner body line through the kick.',
    primaryCue: 'Heels come up, knees stay inside the hips.',
    cueTheme: 'Narrow recovery, strong foot pressure.',
    bestFor: 'Swimmers whose breaststroke kick creates drag or loses symmetry.',
    equipment: 'Wall, pull buoy, or light band',
    diffRange: 'Beginner - Intermediate',
    whenToUse: 'Use before tempo work or any set where wide knees appear under fatigue.',
    whenNotToUse: 'Avoid forcing range if the swimmer reports knee pain.',
    matchKeywords: ['breaststroke', 'knee width', 'wide knees', 'narrow kick', 'pull buoy'],
  },
  {
    id: 'breaststroke-pull-breath-timing',
    title: 'Breaststroke Pull & Breath Timing',
    stroke: 'Breaststroke',
    phases: ['Pull', 'Breathing', 'Timing'],
    faults: ['Head lifts early', 'Pull too wide', 'Breath breaks rhythm'],
    objective: 'Coordinate the small pull, quick breath, and forward recovery without lifting the body out of line.',
    primaryCue: 'Hands press, eyes rise, shoot forward.',
    cueTheme: 'Small pull, quick breath, forward recovery.',
    bestFor: 'Swimmers who over-pull or breathe late in breaststroke.',
    equipment: 'None or pull buoy',
    diffRange: 'Intermediate',
    whenToUse: 'Use after the kick pattern is stable and before full-stroke race rhythm.',
    whenNotToUse: 'Not first priority if the kick is still uncontrolled.',
    matchKeywords: ['breaststroke', 'pull', 'breath', 'timing', 'shoot forward'],
  },
  {
    id: 'freestyle-body-line',
    title: 'Freestyle Body Line',
    stroke: 'Freestyle',
    phases: ['Body Line', 'Rotation'],
    faults: ['Sinking hips', 'High head', 'Body line breaks while kicking'],
    objective: 'Create a long, quiet body line so the swimmer can hold hips high before adding harder catch work.',
    primaryCue: 'Press the chest, lengthen the spine, let the hips ride high.',
    cueTheme: 'Long vessel, quiet head, high hips.',
    bestFor: 'Freestyle swimmers who fight the water before the catch begins.',
    equipment: 'Fins optional',
    diffRange: 'Beginner - Intermediate',
    whenToUse: 'Use at the start of freestyle technique sessions and after fatigue breaks posture.',
    whenNotToUse: 'Do not overuse if the swimmer already holds stable posture and needs propulsion work.',
    matchKeywords: ['freestyle', 'body line', 'hips', 'head', 'posture'],
  },
  {
    id: 'freestyle-catch-position',
    title: 'Freestyle Catch Position',
    stroke: 'Freestyle',
    phases: ['Catch', 'Pull'],
    faults: ['Dropped elbow', 'Pressing down', 'Slipping water'],
    objective: 'Build an early catch shape with the fingertips down and forearm connected to the water.',
    primaryCue: 'Fingertips down, elbow stays proud.',
    cueTheme: 'Feel pressure on hand and forearm before pulling.',
    bestFor: 'Swimmers with weak propulsion or an elbow that collapses at the front.',
    equipment: 'Snorkel, paddles optional',
    diffRange: 'Intermediate - Advanced',
    whenToUse: 'Use at low to moderate intensity where the swimmer can feel water pressure.',
    whenNotToUse: 'Avoid heavy paddles if the swimmer cannot hold the shape without them.',
    matchKeywords: ['freestyle', 'catch', 'elbow', 'forearm', 'scull'],
  },
  {
    id: 'freestyle-breathing-control',
    title: 'Freestyle Breathing Control',
    stroke: 'Freestyle',
    phases: ['Breathing', 'Rotation'],
    faults: ['Head lifts to breathe', 'Over-rotation', 'Late breath'],
    objective: 'Keep the breath low and connected to rotation so the body line stays intact.',
    primaryCue: 'One goggle in, one goggle out.',
    cueTheme: 'Low breath, stable lead arm, smooth return.',
    bestFor: 'Swimmers whose hips drop or rhythm breaks every time they breathe.',
    equipment: 'Fins optional',
    diffRange: 'Beginner - Intermediate',
    whenToUse: 'Use in aerobic technique work before adding speed.',
    whenNotToUse: 'Avoid breath-control pressure for anxious or very new swimmers.',
    matchKeywords: ['freestyle', 'breathing', 'one goggle', 'rotation', 'head'],
  },
  {
    id: 'backstroke-hip-position',
    title: 'Backstroke Hip Position',
    stroke: 'Backstroke',
    phases: ['Body Line', 'Rotation', 'Kick Drive'],
    faults: ['Dropped hips', 'Knees break surface', 'Flat body position'],
    objective: 'Hold a high-hip backstroke line with steady rotation and a compact kick.',
    primaryCue: 'Belly up, hips high, kick under the surface.',
    cueTheme: 'Tall posture on the back with quiet knees.',
    bestFor: 'Backstrokers who sit low or kick from the knees.',
    equipment: 'Fins, cup optional',
    diffRange: 'Beginner - Intermediate',
    whenToUse: 'Use early in backstroke blocks and after hard sets when posture collapses.',
    whenNotToUse: 'Do not chase speed until the swimmer can hold the line.',
    matchKeywords: ['backstroke', 'hip', 'body line', 'kick', 'rotation'],
  },
  {
    id: 'butterfly-rhythm-body-wave',
    title: 'Butterfly Rhythm & Body Wave',
    stroke: 'Butterfly',
    phases: ['Timing', 'Body Line', 'Breathing'],
    faults: ['Flat body wave', 'Late second kick', 'High breath'],
    objective: 'Connect body wave, two-beat kick timing, and low breath position without forcing the stroke.',
    primaryCue: 'Kick in, kick out, breathe low.',
    cueTheme: 'Rhythm first, power second.',
    bestFor: 'Swimmers who muscle butterfly instead of riding the rhythm.',
    equipment: 'Fins recommended',
    diffRange: 'Intermediate - Advanced',
    whenToUse: 'Use with short repeats and plenty of rest so rhythm stays clean.',
    whenNotToUse: 'Avoid long fatigue sets while rebuilding timing.',
    matchKeywords: ['butterfly', 'body wave', 'rhythm', 'dolphin', 'second kick'],
  },
  {
    id: 'streamline-starts-turns',
    title: 'Streamline / Starts / Turns',
    stroke: 'General',
    phases: ['Start', 'Turn', 'Underwater', 'Breakout'],
    faults: ['Loose streamline', 'Early breakout', 'Weak push-off'],
    objective: 'Improve wall speed, underwater line, and breakout timing across all strokes.',
    primaryCue: 'Lock the line before you leave the wall.',
    cueTheme: 'Tight streamline, patient breakout, fast first stroke.',
    bestFor: 'Any competitive swimmer losing speed off starts or turns.',
    equipment: 'None or fins',
    diffRange: 'Beginner - Elite',
    whenToUse: 'Use every week in small doses, especially before race preparation.',
    whenNotToUse: 'Keep volume low for younger swimmers who cannot hold breath comfortably.',
    matchKeywords: ['streamline', 'start', 'turn', 'underwater', 'breakout'],
  },
];

const drill = ({
  id,
  title,
  stroke,
  phase,
  pack_ids,
  fault_tags,
  purpose,
  coaching_cue,
  setup,
  execution_steps,
  common_mistakes,
  progression,
  difficulty = 'Intermediate',
  equipment = 'none',
  duration_or_reps = '4 x 25m easy technique',
  regression = '',
  safety_notes = 'None.',
}) => ({
  id,
  title,
  stroke,
  phase,
  pack_ids,
  fault_tags,
  purpose,
  coaching_cue,
  coaching_cues: coaching_cue,
  setup,
  execution_steps,
  instructions: execution_steps.join(' '),
  common_mistakes,
  progression,
  regression,
  difficulty,
  equipment,
  duration_or_reps,
  safety_notes,
  is_default: true,
  is_active: true,
  visibility: 'shared_default',
  club_id: null,
});

export const DEFAULT_DRILLS = [
  drill({
    id: 'bs-heel-recovery-pause',
    title: 'Heel Recovery Pause Kick',
    stroke: 'Breaststroke',
    phase: 'Kick Recovery',
    pack_ids: ['breaststroke-kick-timing'],
    fault_tags: 'kick timing, heel recovery, early foot turn, breaststroke',
    purpose: 'Teaches swimmers to bring the heels up before turning the feet out.',
    coaching_cue: 'Heels first, feet turn last.',
    setup: 'Hold the wall or use a kickboard at easy effort.',
    execution_steps: ['Recover heels slowly to the seat.', 'Pause for one count.', 'Turn feet out and snap together.', 'Glide for one beat before repeating.'],
    common_mistakes: 'Turning the feet before the heels rise|Rushing the snap|Letting knees drift wide',
    progression: 'Remove the pause and keep the same sequence at normal rhythm.',
    difficulty: 'Beginner',
    equipment: 'wall or board',
  }),
  drill({
    id: 'bs-kick-glide-count',
    title: 'Kick-Glide Count Drill',
    stroke: 'Breaststroke',
    phase: 'Timing',
    pack_ids: ['breaststroke-kick-timing'],
    fault_tags: 'kick timing, glide, rushed kick, breaststroke',
    purpose: 'Connects a clean kick finish to a short controlled glide.',
    coaching_cue: 'Snap, squeeze, ride the line.',
    setup: 'Push off in streamline and work at low speed.',
    execution_steps: ['Complete one breaststroke kick.', 'Squeeze feet together.', 'Count one beat in glide.', 'Repeat without adding a pull.'],
    common_mistakes: 'No glide after the kick|Looking forward|Letting feet separate after the snap',
    progression: 'Move to full stroke with the same one-beat glide.',
    difficulty: 'Beginner',
  }),
  drill({
    id: 'bs-2-kicks-1-pull',
    title: 'Two Kicks One Pull',
    stroke: 'Breaststroke',
    phase: 'Timing',
    pack_ids: ['breaststroke-kick-timing', 'breaststroke-pull-breath-timing'],
    fault_tags: 'kick timing, pull timing, glide, breaststroke',
    purpose: 'Gives extra time to feel kick completion before the next pull.',
    coaching_cue: 'Finish both kicks before the hands move.',
    setup: 'Swim breaststroke with two kicks for every arm pull.',
    execution_steps: ['Pull and breathe once.', 'Recover forward.', 'Complete two controlled kicks.', 'Start the next pull only after the second glide.'],
    common_mistakes: 'Starting the pull during the kick|Over-gliding until speed stops|Lifting the head between kicks',
    progression: 'Alternate 25m two-kick drill with 25m full stroke.',
    equipment: 'none',
  }),
  drill({
    id: 'bs-snap-finish-line',
    title: 'Snap Finish Line Drill',
    stroke: 'Breaststroke',
    phase: 'Kick Drive',
    pack_ids: ['breaststroke-kick-timing'],
    fault_tags: 'weak snap, kick finish, breaststroke kick',
    purpose: 'Sharpens the final squeeze of the feet so the kick finishes narrow and fast.',
    coaching_cue: 'Snap the heels together behind the line.',
    setup: 'Use short repeats with full rest.',
    execution_steps: ['Kick breaststroke on front or back.', 'Focus only on the final foot snap.', 'Finish with toes pointed and legs long.', 'Reset before the next kick.'],
    common_mistakes: 'Soft finish|Feet finishing apart|Bending knees again after the snap',
    progression: 'Add full stroke while keeping the same kick finish.',
    difficulty: 'Intermediate',
  }),
  drill({
    id: 'bs-wall-narrow-kick',
    title: 'Wall Narrow-Knee Kick',
    stroke: 'Breaststroke',
    phase: 'Kick Recovery',
    pack_ids: ['breaststroke-knee-width-control'],
    fault_tags: 'wide knees, knee width, narrow kick, breaststroke',
    purpose: 'Creates visual feedback for knee width during kick recovery.',
    coaching_cue: 'Knees inside the hips.',
    setup: 'Face the wall with hands on the gutter.',
    execution_steps: ['Set hips close to the surface.', 'Recover heels without flaring knees.', 'Watch knee width against the body line.', 'Snap and squeeze feet together.'],
    common_mistakes: 'Knees opening wider than hips|Hips dropping|Pulling knees under the belly',
    progression: 'Move from wall to kickboard while keeping the same width.',
    difficulty: 'Beginner',
    equipment: 'wall',
  }),
  drill({
    id: 'bs-pull-buoy-knee-track',
    title: 'Pull Buoy Knee Track Kick',
    stroke: 'Breaststroke',
    phase: 'Kick Recovery',
    pack_ids: ['breaststroke-knee-width-control'],
    fault_tags: 'wide knees, knee control, pull buoy, breaststroke kick',
    purpose: 'Gives immediate feedback when the knees separate too much.',
    coaching_cue: 'Hold the buoy lightly, kick from the feet.',
    setup: 'Place a small pull buoy between the knees.',
    execution_steps: ['Keep light contact with the buoy.', 'Recover heels slowly.', 'Turn feet out without squeezing hard.', 'Snap and return to a long line.'],
    common_mistakes: 'Crushing the buoy|Losing foot pressure|Cycling the knees forward',
    progression: 'Remove the buoy and repeat the same narrow recovery.',
    equipment: 'pull buoy',
  }),
  drill({
    id: 'bs-back-kick-line',
    title: 'Back Breaststroke Kick Line',
    stroke: 'Breaststroke',
    phase: 'Kick Drive',
    pack_ids: ['breaststroke-knee-width-control'],
    fault_tags: 'knee width, kick path, asymmetric kick, breaststroke',
    purpose: 'Lets the coach see the kick path and helps the swimmer feel foot pressure.',
    coaching_cue: 'Show the soles, then squeeze the line.',
    setup: 'Swim on the back with arms by side or streamlined.',
    execution_steps: ['Recover heels under the water.', 'Keep knees from popping wide.', 'Press soles back against the water.', 'Finish long and narrow.'],
    common_mistakes: 'Knees breaking high|Feet missing water|Uneven kick finish',
    progression: 'Alternate back kick and normal breaststroke kick.',
    difficulty: 'Intermediate',
  }),
  drill({
    id: 'bs-band-awareness-kick',
    title: 'Light Band Awareness Kick',
    stroke: 'Breaststroke',
    phase: 'Kick Recovery',
    pack_ids: ['breaststroke-knee-width-control'],
    fault_tags: 'wide knees, hip control, knee width, breaststroke',
    purpose: 'Builds awareness of excessive knee separation without forcing the joint.',
    coaching_cue: 'Feel the band, do not fight it.',
    setup: 'Use a light band above the knees only with coach supervision.',
    execution_steps: ['Kick slowly for short repeats.', 'Keep band tension light.', 'Recover heels without pushing knees outward.', 'Stop if knee discomfort appears.'],
    common_mistakes: 'Using a band that is too tight|Forcing range|Ignoring knee discomfort',
    progression: 'Remove the band and keep the same recovery path.',
    difficulty: 'Advanced',
    equipment: 'light band',
    safety_notes: 'Stop immediately if the swimmer reports knee pain.',
  }),
  drill({
    id: 'bs-small-pull-breath',
    title: 'Small Pull Breath Drill',
    stroke: 'Breaststroke',
    phase: 'Pull',
    pack_ids: ['breaststroke-pull-breath-timing'],
    fault_tags: 'over-pull, breath timing, breaststroke pull',
    purpose: 'Prevents the pull from sweeping too wide or too far back.',
    coaching_cue: 'Small heart shape, quick breath.',
    setup: 'Swim easy breaststroke focusing on arm path only.',
    execution_steps: ['Press out slightly.', 'Sweep in under the chin.', 'Breathe as the hands gather.', 'Shoot hands forward before kicking.'],
    common_mistakes: 'Pulling past the shoulders|Breathing after the hands recover|Dropping elbows',
    progression: 'Add tempo while keeping the pull small.',
  }),
  drill({
    id: 'bs-shoot-forward',
    title: 'Shoot Forward Recovery',
    stroke: 'Breaststroke',
    phase: 'Recovery',
    pack_ids: ['breaststroke-pull-breath-timing'],
    fault_tags: 'slow recovery, breath timing, dropped hips, breaststroke',
    purpose: 'Trains a fast forward hand recovery after the breath.',
    coaching_cue: 'Breathe, then shoot the hands to the wall.',
    setup: 'Use short 12.5m or 25m repeats.',
    execution_steps: ['Start the pull small.', 'Take a quick breath.', 'Drive both hands forward together.', 'Let the kick finish the line.'],
    common_mistakes: 'Pausing under the chin|Throwing the head up|Hands diving too deep',
    progression: 'Use a slightly faster tempo without losing line.',
  }),
  drill({
    id: 'bs-pull-kick-separate',
    title: 'Pull-Kick Separation Drill',
    stroke: 'Breaststroke',
    phase: 'Timing',
    pack_ids: ['breaststroke-pull-breath-timing'],
    fault_tags: 'pull timing, kick timing, rushed rhythm, breaststroke',
    purpose: 'Separates the actions so the swimmer stops pulling and kicking at the same time.',
    coaching_cue: 'Pull first, kick second.',
    setup: 'Swim slowly with a deliberate rhythm.',
    execution_steps: ['Pull and breathe.', 'Recover the hands fully forward.', 'Then kick and glide.', 'Repeat with quiet head position.'],
    common_mistakes: 'Kicking while the hands are still under the body|Over-gliding|Rushing the breath',
    progression: 'Reduce the pause until the timing becomes full-stroke rhythm.',
    difficulty: 'Beginner',
  }),
  drill({
    id: 'bs-low-breath-line',
    title: 'Low Breath Line Drill',
    stroke: 'Breaststroke',
    phase: 'Breathing',
    pack_ids: ['breaststroke-pull-breath-timing'],
    fault_tags: 'high breath, head lift, dropped hips, breaststroke',
    purpose: 'Keeps the breath forward and low so the hips do not drop.',
    coaching_cue: 'Eyes forward, chin low, hands forward.',
    setup: 'Swim at easy effort with coach watching from the side.',
    execution_steps: ['Let the pull lift the breath.', 'Keep the chin close to the surface.', 'Return eyes down as hands shoot forward.', 'Kick after the hands recover.'],
    common_mistakes: 'Looking at the end wall|Breathing too late|Arching the back',
    progression: 'Alternate drill lengths with normal breaststroke.',
  }),
  drill({
    id: 'fr-streamline-kick',
    title: 'Streamline Flutter Kick',
    stroke: 'Freestyle',
    phase: 'Body Line',
    pack_ids: ['freestyle-body-line', 'streamline-starts-turns'],
    fault_tags: 'body line, sinking hips, high head, freestyle',
    purpose: 'Builds a long freestyle line without arm timing distractions.',
    coaching_cue: 'Long neck, ribs quiet, hips high.',
    setup: 'Push off in streamline and kick easy.',
    execution_steps: ['Lock hands in streamline.', 'Look down.', 'Kick small from the hips.', 'Hold the body line until speed fades.'],
    common_mistakes: 'Kicking from the knees|Looking forward|Arching the lower back',
    progression: 'Add six kicks then one stroke while preserving the line.',
    difficulty: 'Beginner',
  }),
  drill({
    id: 'fr-side-kick-switch',
    title: 'Side Kick Switch',
    stroke: 'Freestyle',
    phase: 'Rotation',
    pack_ids: ['freestyle-body-line', 'freestyle-breathing-control'],
    fault_tags: 'rotation, body line, balance, freestyle',
    purpose: 'Develops balance on each side of the freestyle rotation.',
    coaching_cue: 'Long lead arm, hip points to the wall.',
    setup: 'Kick on one side with bottom arm extended.',
    execution_steps: ['Hold six kicks on one side.', 'Take one smooth stroke to switch.', 'Hold six kicks on the other side.', 'Keep the head still unless breathing.'],
    common_mistakes: 'Rolling onto the back|Lead arm dropping|Scissor kick during switch',
    progression: 'Use 6-3-6 with three full strokes between sides.',
    equipment: 'fins optional',
  }),
  drill({
    id: 'fr-head-still-kick',
    title: 'Head-Still Kick With Board',
    stroke: 'Freestyle',
    phase: 'Body Line',
    pack_ids: ['freestyle-body-line'],
    fault_tags: 'high head, sinking hips, body line, freestyle',
    purpose: 'Shows how head position affects hip height.',
    coaching_cue: 'Eyes down, water over the cap.',
    setup: 'Use a board lightly, not as a flotation crutch.',
    execution_steps: ['Hold the board low in the water.', 'Look down between the arms.', 'Kick small and steady.', 'Keep hips near the surface.'],
    common_mistakes: 'Pressing down on the board|Looking forward|Large knee bend',
    progression: 'Remove the board and repeat in streamline.',
    difficulty: 'Beginner',
    equipment: 'board',
  }),
  drill({
    id: 'fr-line-to-catch',
    title: 'Body Line To Catch',
    stroke: 'Freestyle',
    phase: 'Body Line',
    pack_ids: ['freestyle-body-line', 'freestyle-catch-position'],
    fault_tags: 'body line, catch setup, freestyle',
    purpose: 'Connects posture to a stable front-end catch.',
    coaching_cue: 'Set the line before you press the water.',
    setup: 'Swim slow freestyle with a brief front-end extension.',
    execution_steps: ['Reach forward without dropping the wrist.', 'Hold the body line for half a beat.', 'Tip fingertips down into catch.', 'Pull only after pressure builds.'],
    common_mistakes: 'Pausing too long|Crossing over|Pressing down instead of catching',
    progression: 'Remove the pause and keep the same catch setup.',
  }),
  drill({
    id: 'fr-front-scull',
    title: 'Front Scull',
    stroke: 'Freestyle',
    phase: 'Catch',
    pack_ids: ['freestyle-catch-position'],
    fault_tags: 'catch, feel for water, forearm pressure, freestyle',
    purpose: 'Builds hand and forearm awareness at the start of the catch.',
    coaching_cue: 'Feel pressure, do not push down.',
    setup: 'Use a snorkel if available to keep the head quiet.',
    execution_steps: ['Extend arms in front.', 'Angle fingertips slightly down.', 'Sweep hands in and out small.', 'Keep elbows higher than hands.'],
    common_mistakes: 'Large sweeping motions|Dropping elbows|Kicking too hard',
    progression: 'Scull for six beats, then swim six strokes.',
    equipment: 'snorkel optional',
  }),
  drill({
    id: 'fr-fist-drill',
    title: 'Fist Drill',
    stroke: 'Freestyle',
    phase: 'Catch',
    pack_ids: ['freestyle-catch-position'],
    fault_tags: 'catch, forearm, slipping water, freestyle',
    purpose: 'Forces the swimmer to use the forearm rather than only the hand.',
    coaching_cue: 'Hold water with the whole forearm.',
    setup: 'Swim freestyle with closed fists.',
    execution_steps: ['Close both fists lightly.', 'Keep the elbow high during catch.', 'Feel pressure on forearm.', 'Open hands after 12.5m and compare feel.'],
    common_mistakes: 'Spinning arms faster|Dropping the elbow|Losing body line',
    progression: 'Alternate fist drill and normal swim by 25m.',
    difficulty: 'Beginner',
  }),
  drill({
    id: 'fr-single-arm-catch',
    title: 'Single Arm Catch Hold',
    stroke: 'Freestyle',
    phase: 'Pull',
    pack_ids: ['freestyle-catch-position'],
    fault_tags: 'catch position, high elbow, pull path, freestyle',
    purpose: 'Lets the swimmer focus on one catch shape at a time.',
    coaching_cue: 'Anchor first, then move past the hand.',
    setup: 'One arm extended, one arm stroking; breathe to the stroking side as needed.',
    execution_steps: ['Hold the lead arm long.', 'Tip fingertips down.', 'Keep elbow above hand.', 'Pull past the anchor point.'],
    common_mistakes: 'Lead arm sinking|Pulling straight down|Over-rotating to breathe',
    progression: 'Switch to three strokes right, three strokes left.',
    equipment: 'fins optional',
  }),
  drill({
    id: 'fr-evf-paddle-tap',
    title: 'EVF Paddle Tap',
    stroke: 'Freestyle',
    phase: 'Catch',
    pack_ids: ['freestyle-catch-position'],
    fault_tags: 'early vertical forearm, dropped elbow, catch, freestyle',
    purpose: 'Uses light paddle feedback to keep the fingertips pitched down.',
    coaching_cue: 'Show the paddle face to the wall behind you.',
    setup: 'Use small paddles only if the swimmer can hold shape safely.',
    execution_steps: ['Swim slowly with small paddles.', 'Set the catch before force.', 'Keep elbow proud.', 'Stop if shoulder discomfort appears.'],
    common_mistakes: 'Using large paddles|Muscling the pull|Losing rotation',
    progression: 'Remove paddles and keep the same hand angle.',
    difficulty: 'Advanced',
    equipment: 'small paddles',
    safety_notes: 'Avoid paddles for swimmers with shoulder pain.',
  }),
  drill({
    id: 'fr-one-goggle-breath',
    title: 'One-Goggle Breath',
    stroke: 'Freestyle',
    phase: 'Breathing',
    pack_ids: ['freestyle-breathing-control'],
    fault_tags: 'breathing, head lift, low breath, freestyle',
    purpose: 'Keeps the breath low so the head does not lift and sink the hips.',
    coaching_cue: 'One goggle in, one goggle out.',
    setup: 'Swim easy freestyle breathing every three or four strokes.',
    execution_steps: ['Rotate the head with the body.', 'Keep one lens in the water.', 'Return the face before the stroking arm enters.', 'Keep the lead arm patient.'],
    common_mistakes: 'Lifting to breathe|Looking backward|Dropping the lead arm',
    progression: 'Use the same breath at moderate pace.',
    difficulty: 'Beginner',
  }),
  drill({
    id: 'fr-bubble-bubble-breathe',
    title: 'Bubble-Bubble-Breathe',
    stroke: 'Freestyle',
    phase: 'Breathing',
    pack_ids: ['freestyle-breathing-control'],
    fault_tags: 'breath timing, exhale, freestyle breathing',
    purpose: 'Teaches steady exhale so the breath can stay quick and low.',
    coaching_cue: 'Blow before you go.',
    setup: 'Use relaxed 25m repeats.',
    execution_steps: ['Exhale steadily for two strokes.', 'Turn to breathe without pausing.', 'Return face down immediately.', 'Resume bubbles before the next breath.'],
    common_mistakes: 'Holding breath underwater|Breathing late|Over-rotating',
    progression: 'Add bilateral breathing if appropriate.',
  }),
  drill({
    id: 'fr-breath-with-fins',
    title: 'Fins Low-Breath Rhythm',
    stroke: 'Freestyle',
    phase: 'Breathing',
    pack_ids: ['freestyle-breathing-control'],
    fault_tags: 'breathing rhythm, body line, freestyle',
    purpose: 'Uses fins to support speed while the swimmer focuses on calm breathing.',
    coaching_cue: 'Let the body roll the breath open.',
    setup: 'Wear fins and swim at controlled aerobic effort.',
    execution_steps: ['Kick steady from the hips.', 'Rotate to breathe with one goggle in.', 'Keep the lead arm extended.', 'Return to line before the next catch.'],
    common_mistakes: 'Kicking too hard|Pausing the lead arm too long|Lifting the chin',
    progression: 'Remove fins and repeat short repeats.',
    equipment: 'fins',
  }),
  drill({
    id: 'fr-breath-reset-6-1-6',
    title: '6-1-6 Breath Reset',
    stroke: 'Freestyle',
    phase: 'Breathing',
    pack_ids: ['freestyle-breathing-control', 'freestyle-body-line'],
    fault_tags: 'breathing, rotation, balance, freestyle',
    purpose: 'Links side balance with a controlled breath and stroke switch.',
    coaching_cue: 'Breathe from the side balance, not from a lift.',
    setup: 'Kick six beats on one side, stroke once, then switch.',
    execution_steps: ['Start on side with one arm extended.', 'Take one low breath.', 'Stroke once to switch sides.', 'Repeat on the other side.'],
    common_mistakes: 'Rolling onto back|Lead arm sinking|Kick stopping during breath',
    progression: 'Move to 6-3-6 with three strokes between sides.',
    equipment: 'fins optional',
  }),
  drill({
    id: 'bk-cup-balance',
    title: 'Backstroke Cup Balance',
    stroke: 'Backstroke',
    phase: 'Body Line',
    pack_ids: ['backstroke-hip-position'],
    fault_tags: 'head stability, dropped hips, backstroke body line',
    purpose: 'Encourages still head position so the hips can stay high.',
    coaching_cue: 'Eyes still, belly up.',
    setup: 'Place a small plastic cup on the forehead if safe and appropriate.',
    execution_steps: ['Float tall on the back.', 'Kick gently under the surface.', 'Keep eyes fixed upward.', 'Swim without spilling the cup.'],
    common_mistakes: 'Tucking the chin|Knees breaking the surface|Over-kicking',
    progression: 'Remove the cup and keep the same head position.',
    difficulty: 'Beginner',
    equipment: 'cup optional',
  }),
  drill({
    id: 'bk-hip-lift-kick',
    title: 'Backstroke Hip-Lift Kick',
    stroke: 'Backstroke',
    phase: 'Kick Drive',
    pack_ids: ['backstroke-hip-position'],
    fault_tags: 'dropped hips, knee kick, backstroke',
    purpose: 'Shows the swimmer how to keep hips near the surface while kicking.',
    coaching_cue: 'Push the belt buckle to the sky.',
    setup: 'Arms by side or streamlined on back.',
    execution_steps: ['Set the head still.', 'Lift hips gently toward the surface.', 'Kick small from the hips.', 'Keep knees below the surface.'],
    common_mistakes: 'Bending knees too much|Arching the back|Holding breath',
    progression: 'Add single-arm backstroke while keeping hips high.',
  }),
  drill({
    id: 'bk-rotation-kick',
    title: 'Backstroke Rotation Kick',
    stroke: 'Backstroke',
    phase: 'Rotation',
    pack_ids: ['backstroke-hip-position'],
    fault_tags: 'flat body, hip position, backstroke rotation',
    purpose: 'Connects hip position to controlled shoulder rotation.',
    coaching_cue: 'Rotate around a tall spine.',
    setup: 'Kick on back with one shoulder slightly lifted.',
    execution_steps: ['Hold six kicks rotated to one side.', 'Switch through the middle without lifting the head.', 'Hold six kicks on the other side.', 'Keep hips near the surface.'],
    common_mistakes: 'Head turning with shoulders|Hips sinking during switch|Wide kick',
    progression: 'Add three backstroke pulls between rotations.',
    equipment: 'fins optional',
  }),
  drill({
    id: 'bk-single-arm-posture',
    title: 'Single-Arm Backstroke Posture',
    stroke: 'Backstroke',
    phase: 'Entry',
    pack_ids: ['backstroke-hip-position'],
    fault_tags: 'backstroke posture, dropped hips, rotation',
    purpose: 'Allows one-arm focus while preserving the high-hip line.',
    coaching_cue: 'Reach long without sitting down.',
    setup: 'One arm stays at side while the other strokes.',
    execution_steps: ['Set a tall body line.', 'Stroke one arm with smooth rotation.', 'Keep the kick compact.', 'Switch arms after 12.5m or 25m.'],
    common_mistakes: 'Sitting during recovery|Crossing over|Kicking wider to balance',
    progression: 'Return to full backstroke with the same posture.',
  }),
  drill({
    id: 'fly-body-dolphin',
    title: 'Body Dolphin',
    stroke: 'Butterfly',
    phase: 'Body Line',
    pack_ids: ['butterfly-rhythm-body-wave', 'streamline-starts-turns'],
    fault_tags: 'body wave, dolphin kick, butterfly rhythm',
    purpose: 'Builds a wave from chest to hips without arm timing.',
    coaching_cue: 'Chest presses, hips answer.',
    setup: 'Arms by side or in streamline with fins if needed.',
    execution_steps: ['Press the chest slightly.', 'Let hips rise as the wave travels.', 'Kick from the hips.', 'Keep the head low.'],
    common_mistakes: 'Kicking only from knees|Diving too deep|Lifting the head',
    progression: 'Add one-arm butterfly after body dolphin repeats.',
    equipment: 'fins optional',
  }),
  drill({
    id: 'fly-single-arm-rhythm',
    title: 'Single-Arm Butterfly Rhythm',
    stroke: 'Butterfly',
    phase: 'Timing',
    pack_ids: ['butterfly-rhythm-body-wave'],
    fault_tags: 'butterfly timing, second kick, breathing',
    purpose: 'Simplifies butterfly timing while keeping the two-kick rhythm.',
    coaching_cue: 'Kick in, kick out.',
    setup: 'One arm strokes while the other stays forward or by side.',
    execution_steps: ['Kick as the hand enters.', 'Press through the pull.', 'Kick as the hand exits.', 'Breathe low when needed.'],
    common_mistakes: 'Missing the second kick|Breathing too high|Straight-arm muscling',
    progression: 'Alternate single-arm and full butterfly by 12.5m.',
    difficulty: 'Intermediate',
    equipment: 'fins recommended',
  }),
  drill({
    id: 'fly-3-3-3',
    title: '3-3-3 Butterfly',
    stroke: 'Butterfly',
    phase: 'Timing',
    pack_ids: ['butterfly-rhythm-body-wave'],
    fault_tags: 'butterfly rhythm, body wave, timing',
    purpose: 'Transfers single-arm rhythm into full-stroke butterfly.',
    coaching_cue: 'Same rhythm, different arm pattern.',
    setup: 'Swim three right-arm, three left-arm, three full strokes.',
    execution_steps: ['Complete three right-arm strokes.', 'Complete three left-arm strokes.', 'Complete three full strokes.', 'Keep the two-kick rhythm consistent.'],
    common_mistakes: 'Changing tempo on full stroke|High breath|Flat body line',
    progression: 'Use 2-2-2, then full butterfly.',
    equipment: 'fins optional',
  }),
  drill({
    id: 'fly-low-breath',
    title: 'Low Breath Butterfly',
    stroke: 'Butterfly',
    phase: 'Breathing',
    pack_ids: ['butterfly-rhythm-body-wave'],
    fault_tags: 'high breath, butterfly timing, dropped hips',
    purpose: 'Keeps the breath low so the rhythm and hips do not collapse.',
    coaching_cue: 'Breathe forward, not up.',
    setup: 'Use short repeats with plenty of rest.',
    execution_steps: ['Start with body wave rhythm.', 'Let the breath skim forward.', 'Return the face before hand entry.', 'Keep the second kick connected.'],
    common_mistakes: 'Looking forward too long|Late face return|Forcing the arms over water',
    progression: 'Add one extra full-stroke cycle while holding the low breath.',
    difficulty: 'Advanced',
  }),
  drill({
    id: 'st-wall-streamline-lock',
    title: 'Wall Streamline Lock',
    stroke: 'General',
    phase: 'Underwater',
    pack_ids: ['streamline-starts-turns'],
    fault_tags: 'streamline, push-off, underwater, starts and turns',
    purpose: 'Builds a tight line before adding kick or breakout timing.',
    coaching_cue: 'Lock hands, squeeze ears, ribs quiet.',
    setup: 'Push off from the wall in streamline.',
    execution_steps: ['Set hands locked before push.', 'Squeeze ears with upper arms.', 'Push off and hold line.', 'Stop before the line loosens.'],
    common_mistakes: 'Hands separating|Head lifted|Fluttering legs immediately',
    progression: 'Add three dolphin kicks before breakout.',
    difficulty: 'Beginner',
  }),
  drill({
    id: 'st-dolphin-count',
    title: 'Dolphin Kick Count Breakout',
    stroke: 'General',
    phase: 'Breakout',
    pack_ids: ['streamline-starts-turns'],
    fault_tags: 'breakout, underwater, dolphin kick, streamline',
    purpose: 'Finds the best number of underwater kicks before speed drops.',
    coaching_cue: 'Break out before the line slows.',
    setup: 'Use push-offs with coach timing or visual feedback.',
    execution_steps: ['Push off in tight streamline.', 'Take a set number of dolphin kicks.', 'Break out with speed.', 'Compare speed across different counts.'],
    common_mistakes: 'Staying under too long|Breaking out upward|Loose arms during kicks',
    progression: 'Use the chosen count in race-specific turns.',
    equipment: 'none',
  }),
  drill({
    id: 'st-turn-push-line',
    title: 'Turn Push-Off Line',
    stroke: 'General',
    phase: 'Turn',
    pack_ids: ['streamline-starts-turns'],
    fault_tags: 'turn, push-off, streamline, wall speed',
    purpose: 'Improves the line leaving the wall after a turn.',
    coaching_cue: 'Feet plant, body locks, then push.',
    setup: 'Start close to the wall and perform repeated push-offs.',
    execution_steps: ['Plant feet firmly on the wall.', 'Set streamline before pushing.', 'Push straight through the body line.', 'Hold until speed fades.'],
    common_mistakes: 'Pushing before arms lock|Angled push-off|Looking forward',
    progression: 'Add the turn approach before the push-off.',
    difficulty: 'Beginner',
  }),
  drill({
    id: 'st-first-stroke-timing',
    title: 'First Stroke Breakout Timing',
    stroke: 'General',
    phase: 'Breakout',
    pack_ids: ['streamline-starts-turns'],
    fault_tags: 'breakout timing, first stroke, starts and turns',
    purpose: 'Connects underwater speed to a clean first stroke without popping up.',
    coaching_cue: 'First stroke catches while speed is still there.',
    setup: 'Push off, kick underwater, and take one breakout stroke.',
    execution_steps: ['Leave the wall tight.', 'Hold the chosen kick count.', 'Start the first stroke before surfacing fully.', 'Keep the head low through breakout.'],
    common_mistakes: 'Breathing on the first stroke|Starting the pull too late|Breaking streamline early',
    progression: 'Add two to four full strokes after breakout.',
    difficulty: 'Intermediate',
  }),
];

export function getDefaultDrills() {
  return DEFAULT_DRILLS.map((item) => ({ ...item }));
}

export function getDefaultDrillPacks() {
  return DEFAULT_DRILL_PACKS.map((item) => ({ ...item }));
}
