/**
 * Default reference technical standards library.
 * These are built-in reference standards visible to all clubs.
 * Coaches can duplicate these to create club-specific variants.
 */
export const DEFAULT_STANDARDS = [
  // ─── BREASTSTROKE ───────────────────────────────────────────────────────────
  {
    title: 'Breaststroke Kick Recovery Standard',
    stroke: 'Breaststroke',
    phase: 'Kick Recovery',
    standard_type: 'default_reference',
    visibility: 'shared_default',
    difficulty_level: 'Competitive',
    technical_goal: 'Heels recover high and narrow, knees stay inside hip line, feet remain relaxed until the late turn phase, minimising frontal drag during recovery.',
    key_positions: 'Heels draw up toward the glutes in a narrow path. Knees stay at or inside hip-width. Feet are relaxed and dorsiflexed (toes down) until heels reach bum height. No early outward rotation of the foot.',
    coach_cues: '"Heels first, narrow and high" · "Knees inside hips — no wide knees" · "Feet relaxed until the turn" · "Heel to bum, then turn"',
    common_faults: 'Wide knees (knees flare out beyond hips) · Early foot turn (feet rotate outward before heels are at bum height) · Low heel recovery (feet dragged along, not lifted) · Knees dropping below water line during recovery',
    linked_fault_tags: 'wide_knees,early_foot_turn,low_heel_recovery,breaststroke_recovery',
    linked_drag_zones: 'knees,ankles',
    success_criteria: 'Heels visible rising straight up in underwater footage. Knees inside hip line throughout recovery. No early foot rotation. Drag from knee width reduced on re-check.',
    scoring_guidance: 'Check underwater side and rear footage. Look for knee width relative to hips at peak heel height. Coach marks improvement when knee width reduces across reports.',
    is_active: true,
  },
  {
    title: 'Breaststroke Kick Drive Standard',
    stroke: 'Breaststroke',
    phase: 'Kick Drive',
    standard_type: 'default_reference',
    visibility: 'shared_default',
    difficulty_level: 'Competitive',
    technical_goal: 'Feet turn late and soles press directly backward. Kick finishes long, narrow, and together. Ankles snap into a streamlined position at finish.',
    key_positions: 'Feet turn outward at peak heel height (late turn). Soles angle to press water backward. Kick drives hips and body forward. Feet snap together at finish — toes pointed, ankles together.',
    coach_cues: '"Soles press back — not out" · "Snap together at the finish" · "Long and narrow finish" · "Kick finishes, then glide"',
    common_faults: 'Circular kick (feet sweep wide in an arc rather than press straight back) · Early foot turn (reduces propulsion direction) · Feet separate at finish (breaks streamline) · Short finish (kick stops before maximum propulsion)',
    linked_fault_tags: 'circular_kick,short_kick_finish,feet_separate,breaststroke_drive',
    linked_drag_zones: 'knees,ankles',
    success_criteria: 'Underwater footage shows feet pressing backward not outward. Feet snap together at kick finish. Kick trace is narrow. Re-check shows improved propulsive direction.',
    scoring_guidance: 'Assess kick path from rear underwater angle. Look for backward vs. circular foot path. Improvement = narrower finish, direct backward press.',
    is_active: true,
  },
  {
    title: 'Breaststroke Timing and Glide Standard',
    stroke: 'Breaststroke',
    phase: 'Timing',
    standard_type: 'default_reference',
    visibility: 'shared_default',
    difficulty_level: 'Competitive',
    technical_goal: 'Hands recover forward before the kick finishes. Breath returns to neutral position before the line. Glide is controlled and maintains body line — not passive sink.',
    key_positions: 'Arms extend forward as kick drives back. Head returns to neutral before hands reach full extension. Body stays high and long in glide. Glide exits when speed decreases — no waiting.',
    coach_cues: '"Arms forward as legs kick back" · "Head down before glide" · "Glide is active, not dead" · "Leave before you slow"',
    common_faults: 'Late arm recovery (arms wait until kick is complete) · Head still up during glide (increases drag) · Glide too long (speed lost before next stroke) · Glide too short (stroke rushed before body is in line)',
    linked_fault_tags: 'timing,glide_too_long,late_arm_recovery,head_position_glide',
    linked_drag_zones: 'head,shoulders',
    success_criteria: 'Side footage shows arm extension overlapping with kick finish. Head returns to neutral before glide. Speed not lost before next stroke cycle. Glide duration consistent.',
    scoring_guidance: 'Time recovery-kick overlap from video timestamps. Check head position during glide from side angle. Improvement = coordinated overlap and head neutral during glide.',
    is_active: true,
  },

  // ─── FREESTYLE ──────────────────────────────────────────────────────────────
  {
    title: 'Freestyle Body Line Standard',
    stroke: 'Freestyle',
    phase: 'Body Line',
    standard_type: 'default_reference',
    visibility: 'shared_default',
    difficulty_level: 'Competitive',
    technical_goal: 'Neutral head position, hips near the surface, long line from shoulders through hips to ankles. Kick supports the body line without excessive lift or sinking.',
    key_positions: 'Head neutral — forehead near surface, eyes looking slightly down-forward. Hips at or near water surface. Ankles at or slightly below hips. Kick amplitude 30–40cm. Long body axis maintained.',
    coach_cues: '"Head neutral — press the chest slightly down" · "Hips up — kick from the hip, not the knee" · "Long line head to heel" · "Quiet kick, big line"',
    common_faults: 'High head (causes hip drop, added drag) · Sinking hips (excessive resistance) · Over-kicking (wasted energy, disturbs line) · Shoulder hunching during entry',
    linked_fault_tags: 'high_head,sinking_hips,excessive_kick,body_line,freestyle',
    linked_drag_zones: 'hips,torso,head',
    success_criteria: 'Underwater side footage shows flat body axis. Hips visible near surface. Head neutral. Coach confirms line improvement on re-check.',
    scoring_guidance: 'Draw body line annotation from shoulder to hip to ankle in underwater footage. Deviation from straight line = drag risk. Improvement = line straightens across reviews.',
    is_active: true,
  },
  {
    title: 'Freestyle Catch Standard',
    stroke: 'Freestyle',
    phase: 'Catch',
    standard_type: 'default_reference',
    visibility: 'shared_default',
    difficulty_level: 'Competitive',
    technical_goal: 'Fingertips angle down on entry. Elbow stays high and above the wrist. Pressure moves backward not downward. Body rotation supports catch setup.',
    key_positions: 'Hand enters in line with shoulder. Fingertips point toward the pool floor as wrist bends. Elbow stays bent and elevated. Forearm vertical at catch initiation (Early Vertical Forearm). Shoulder rotates to support.',
    coach_cues: '"Fingertips down — elbow high" · "Feel the water — don\'t slip through it" · "Press back, not down" · "Shoulder leads the catch"',
    common_faults: 'Dropped elbow (elbow below wrist — push water down not back) · Straight arm pull (loss of power) · Crossover entry (causes sway, poor catch angle) · Pulling before EVF established',
    linked_fault_tags: 'dropped_elbow,straight_arm_pull,crossover_entry,poor_catch,freestyle_catch',
    linked_drag_zones: 'arms,shoulders',
    success_criteria: 'Underwater footage shows elbow above wrist at catch. Forearm vertical on initiation. No crossover. Improved pressure application from first stroke.',
    scoring_guidance: 'Assess catch angle from underwater front or side angle. Draw catch angle annotation. Elbow above wrist = passing. Improvement = EVF established earlier.',
    is_active: true,
  },
  {
    title: 'Freestyle Breathing Standard',
    stroke: 'Freestyle',
    phase: 'Breathing',
    standard_type: 'default_reference',
    visibility: 'shared_default',
    difficulty_level: 'Competitive',
    technical_goal: 'Breath occurs in rotation, not with head lift. One goggle remains near the water. Head returns to neutral before hand entry. Hips remain stable during breath.',
    key_positions: 'Head rotates with body — no extra lift. One goggle in water, one above. Mouth at or just above water. Head returns forward before leading hand enters. No hip sway during breath.',
    coach_cues: '"Rotate to breathe, don\'t lift" · "One eye in, one eye out" · "Head back before hand enters" · "Hips stay still"',
    common_faults: 'Head lifting (causes hip drop, drag spike) · Head staying out too long (off-balance recovery) · Late head return (disrupts entry) · Hip sway from late breath',
    linked_fault_tags: 'head_lift_breath,late_head_return,hip_sway_breath,freestyle_breathing',
    linked_drag_zones: 'head,hips',
    success_criteria: 'Footage shows one goggle remains at water level. Head returns neutral before entry. No hip sway visible from rear angle. Breathing pattern consistent.',
    scoring_guidance: 'Assess breathing from underwater side angle. Look for one goggle position and head return timing. Improvement = earlier return, no lift.',
    is_active: true,
  },

  // ─── BACKSTROKE ─────────────────────────────────────────────────────────────
  {
    title: 'Backstroke Entry Standard',
    stroke: 'Backstroke',
    phase: 'Entry',
    standard_type: 'default_reference',
    visibility: 'shared_default',
    difficulty_level: 'Competitive',
    technical_goal: 'Hand enters in line with the shoulder, pinky first, with no crossover. Head remains still throughout. Rotation supports catch setup.',
    key_positions: 'Hand entry at shoulder width — not past centre. Pinky enters water first. Elbow stays bent in recovery. Head perfectly still — no nodding. Shoulder rotation supports reaching catch depth.',
    coach_cues: '"Pinky in — shoulder width" · "No crossover — in line with shoulder" · "Head still on the pillow" · "Rotation after entry — not before"',
    common_faults: 'Crossover entry (hand enters past centre line, causes sway) · Thumb-first entry (shoulder impingement risk, loses catch angle) · Head lifting or nodding during entry · Flat body, no rotation',
    linked_fault_tags: 'crossover_entry,thumb_first_entry,head_nod,flat_backstroke,backstroke_entry',
    linked_drag_zones: 'shoulders,head',
    success_criteria: 'Footage shows pinky-first entry at shoulder width. No crossover. Head still. Rotation visible post-entry. Shoulder pain risk reduced.',
    scoring_guidance: 'Assess from above-water rear or front angle. Draw entry width line. Crossover = fail. Improvement = consistent shoulder-width pinky entry.',
    is_active: true,
  },
  {
    title: 'Backstroke Hip Position Standard',
    stroke: 'Backstroke',
    phase: 'Body Line',
    standard_type: 'default_reference',
    visibility: 'shared_default',
    difficulty_level: 'Competitive',
    technical_goal: 'Hips ride high at the surface. Kick is narrow and continuous. Ribs and hips are aligned in a flat position. Head does not lift.',
    key_positions: 'Hips at or very near water surface. Kick width inside hip line. Continuous kick rhythm. Ribs flat — not arched. Head in a neutral position on "the pillow".',
    coach_cues: '"Hips up — ride high" · "Narrow kick — feet in the shadow of the hips" · "Ribs flat — no arch" · "Ears in the water"',
    common_faults: 'Hips sinking (major drag source) · Wide kick (increases frontal area) · Excessive back arch (drops hips further) · Head too high or too low',
    linked_fault_tags: 'sinking_hips_back,wide_kick_back,arched_back,backstroke_body_line',
    linked_drag_zones: 'hips,torso',
    success_criteria: 'Side footage shows hip position near surface. Kick narrow. Ribs flat. Head neutral. Drag analysis shows reduced hip-area resistance on re-check.',
    scoring_guidance: 'Draw body line from shoulder through hip in side underwater footage. Sinking hips = angle away from flat. Improvement = hip level rises toward surface.',
    is_active: true,
  },

  // ─── BUTTERFLY ──────────────────────────────────────────────────────────────
  {
    title: 'Butterfly Body Wave Standard',
    stroke: 'Butterfly',
    phase: 'Body Line',
    standard_type: 'default_reference',
    visibility: 'shared_default',
    difficulty_level: 'Competitive',
    technical_goal: 'Chest press initiates the body wave rhythm. Hips follow naturally from the chest. Kick finishes the wave. Body does not over-dive or drop too deep.',
    key_positions: 'Chest presses down to initiate wave. Hips rise naturally — not forced up. Second kick drives the finish. Body undulation is forward-travelling, not vertical. Dive depth no more than 30cm below surface.',
    coach_cues: '"Chest starts the wave" · "Let the hips follow — don\'t force them" · "Wave forward, not up-and-down" · "Don\'t dive — skim forward"',
    common_faults: 'Worm kick (excessive vertical movement, no forward travel) · Hip-initiated wave (loses power) · Over-diving (too deep, increases drag and time) · Dead hips (insufficient undulation)',
    linked_fault_tags: 'worm_kick,over_diving,dead_hips,butterfly_wave,hip_initiated_wave',
    linked_drag_zones: 'torso,hips',
    success_criteria: 'Side footage shows chest-led wave. Hips follow naturally. No excessive vertical dive. Wave travels forward. Rhythm consistent across length.',
    scoring_guidance: 'Trace body wave path in side footage. Forward and consistent amplitude = good. Vertical excess or hip-drop = flag. Improvement = forward-travelling wave.',
    is_active: true,
  },
  {
    title: 'Butterfly Second Kick Timing Standard',
    stroke: 'Butterfly',
    phase: 'Timing',
    standard_type: 'default_reference',
    visibility: 'shared_default',
    difficulty_level: 'Competitive',
    technical_goal: 'Second kick drives the hand exit and recovery. Breath returns before hand entry. Rhythm stays connected between kick and arm cycle.',
    key_positions: 'Second kick fires as hands exit water. Arms recover low over water. Head returns before hands re-enter. First kick fires on entry, second on exit. Two kicks per arm cycle.',
    coach_cues: '"Kick as hands leave — kick as hands enter" · "Head back before hands in" · "Two kicks — always" · "Entry, exit, breathe, entry"',
    common_faults: 'Missing second kick (one kick per cycle, major power loss) · Late head return (causes mistimed entry) · Arms entering while breathing (arm drag) · Uneven kick rhythm',
    linked_fault_tags: 'missing_second_kick,late_head_return_fly,mistimed_entry,butterfly_timing',
    linked_drag_zones: 'shoulders,head',
    success_criteria: 'Video shows two distinct kicks per arm cycle. Head returns before hand entry. Rhythm consistent. Reduced energy waste from timing gaps.',
    scoring_guidance: 'Count kicks per stroke cycle in footage. One kick = fail. Two kicks = base standard. Timing quality assessed from head return relative to hand entry.',
    is_active: true,
  },

  // ─── GENERAL ────────────────────────────────────────────────────────────────
  {
    title: 'Streamline Standard',
    stroke: 'General',
    phase: 'Underwater',
    standard_type: 'default_reference',
    visibility: 'shared_default',
    difficulty_level: 'Competitive',
    technical_goal: 'Hands locked, head between arms, ribs controlled, body long and narrow. Breakout occurs before speed fades below stroke speed.',
    key_positions: 'Hands stacked — thumb grip. Arms straight overhead. Chin to chest — head between arms. Ribs pulled down (no arched back). Body forms one straight narrow line. Breakout at or before speed drops below stroke velocity.',
    coach_cues: '"Lock your hands — squeeze the arms" · "Head between arms — chin down" · "Ribs in — long and narrow" · "Breakout before you slow"',
    common_faults: 'Arms wide or bent (breaks streamline, massive drag) · Head above arms (frontal area increases) · Arched back / ribs flared (body line broken) · Breakout too early (speed advantage lost) · Breakout too late (too slow to stroke efficiently)',
    linked_fault_tags: 'broken_streamline,early_breakout,late_breakout,arched_back_streamline,streamline',
    linked_drag_zones: 'streamline,full_body,head,shoulders',
    success_criteria: 'Underwater side footage shows locked hands, head between arms, flat back, narrow body line. Breakout timing consistent with speed curve.',
    scoring_guidance: 'Draw streamline line from hands through body. Any deviation = drag risk. Assess breakout timing from push-off to first stroke. Improvement = tighter line, optimal breakout.',
    is_active: true,
  },
];