import React from 'react';
import { AlertTriangle, XCircle } from 'lucide-react';

/**
 * Shown on any report where analysis_mode is "placeholder" or "error".
 * Coach-internal only — never shown on public share pages or printed PDFs.
 *
 * Props:
 *   analysisMode      — "placeholder" | "error" | "real_pose" | "manual"
 *   aiErrorMessage    — optional string from the AI server
 *   realPoseDetected  — boolean, false means weak/no pose detection
 */
export default function PlaceholderWarningBanner({ analysisMode, aiErrorMessage, realPoseDetected }) {
  const isError = analysisMode === 'error';
  const isPlaceholder = !analysisMode || analysisMode === 'placeholder';
  const isManualReview = analysisMode === 'manual_review' || analysisMode === 'unreliable_pose';

  if (!isPlaceholder && !isError && !isManualReview) return null;

  if (isError) {
    return (
      <div className="print:hidden flex items-start gap-3 p-4 rounded-xl border border-red-300 bg-red-50">
        <XCircle className="w-4 h-4 text-red-600 flex-shrink-0 mt-0.5" />
        <div className="space-y-1">
          <div className="text-xs font-bold text-red-800">AI Processing Failed — No Analysis Available</div>
          <p className="text-[11px] text-red-700 leading-relaxed">
            The AI server was unable to process this video successfully.
            {aiErrorMessage && <> Reason: <strong>{aiErrorMessage}</strong>.</>}
            {' '}No findings have been generated. You can build this report manually by adding coach findings below.
          </p>
        </div>
      </div>
    );
  }

  // Pose ran but detection was too weak for reliable analysis
  if ((isPlaceholder && realPoseDetected === false) || isManualReview) {
    return (
      <div className="print:hidden flex items-start gap-3 p-4 rounded-xl border border-orange-300 bg-orange-50">
        <AlertTriangle className="w-4 h-4 text-orange-600 flex-shrink-0 mt-0.5" />
        <div className="space-y-1">
          <div className="text-xs font-bold text-orange-800">AI Quality Gate Failed — Manual Coach Review Required</div>
          <p className="text-[11px] text-orange-700 leading-relaxed">
            The AI server processed this video, but the evidence did not meet Swim Sight's coach-grade threshold for draft findings.
            {aiErrorMessage && <> <em>{aiErrorMessage}</em></>}
            {' '}No AI findings were generated. Complete a <strong>manual coach review</strong>, or upload clearer footage and retry AI analysis.
          </p>
        </div>
      </div>
    );
  }

  // Legacy placeholder (demo/test result)
  return (
    <div className="print:hidden flex items-start gap-3 p-4 rounded-xl border border-amber-300 bg-amber-50">
      <AlertTriangle className="w-4 h-4 text-amber-600 flex-shrink-0 mt-0.5" />
      <div className="space-y-1">
        <div className="text-xs font-bold text-amber-800">Placeholder AI Result — Coach Review Required</div>
        <p className="text-[11px] text-amber-700 leading-relaxed">
          This report was generated by a structured demo or test pipeline, not real video pose analysis.
          {aiErrorMessage && <> Note: <em>{aiErrorMessage}</em>.</>}
          {' '}Findings are <strong>not derived from measured pose data</strong> and must not be shared with swimmers or parents as real analysis.
          Review and correct every finding before finalising.
        </p>
      </div>
    </div>
  );
}
