export const AVAILABILITY_STATES = Object.freeze([
  'not_started',
  'metadata_ready',
  'frames_sampled',
  'pose_2d_ready',
  'pose_3d_estimated',
  'pose_3d_triangulated',
  'biomechanics_ready',
  'force_estimates_ready',
  'ai_findings_ready',
  'coach_review_required',
  'approved',
  'failed',
]);

export const CONFIDENCE_LEVELS = Object.freeze(['none', 'low', 'moderate', 'high']);

export const SOURCE_LABELS = Object.freeze([
  'manual',
  'template',
  'video_metadata',
  'pose_2d',
  'monocular_estimate',
  'multi_view_triangulated',
  'biomechanics_engine',
  'hydrodynamics_engine',
  'coach_review',
]);

export const POSE_3D_SOURCES = Object.freeze(['monocular_estimate', 'multi_view_triangulated']);
export const MEASUREMENT_TYPES = Object.freeze(['estimated', 'measured', 'not_available']);

export const ARTIFACT_KINDS = Object.freeze([
  'metadata_json',
  'sampled_frames_manifest',
  'pose_2d_json',
  'pose_3d_json',
  'biomechanics_json',
  'force_estimates_json',
  'coach_report_summary',
]);

export const COACH_DECISIONS = Object.freeze([
  'pending',
  'approved',
  'edited',
  'rejected',
  'manual_added',
]);

export const CANONICAL_JOINT_NAMES = Object.freeze([
  'nose',
  'left_eye',
  'right_eye',
  'left_ear',
  'right_ear',
  'left_shoulder',
  'right_shoulder',
  'left_elbow',
  'right_elbow',
  'left_wrist',
  'right_wrist',
  'left_hip',
  'right_hip',
  'left_knee',
  'right_knee',
  'left_ankle',
  'right_ankle',
  'left_heel',
  'right_heel',
  'left_foot_index',
  'right_foot_index',
]);

export const BIOMECHANICS_CONTRACTS = Object.freeze({
  videoMetadata: Object.freeze({
    videoId: 'string|null',
    durationSeconds: 'number|null',
    fps: 'number|null',
    frameCount: 'number|null',
    width: 'number|null',
    height: 'number|null',
    aspectRatio: 'number|null',
    codec: 'string|null',
    containerType: 'string|null',
    fileSizeMb: 'number|null',
    orientation: 'landscape|portrait|square|unknown',
    metadataComplete: 'boolean',
    errors: 'string[]',
    source: 'video_metadata|template',
    warnings: 'string[]',
  }),
  sampledVideoFrame: Object.freeze({
    frameIndex: 'number',
    timestampMs: 'number',
    imageWidth: 'number|null',
    imageHeight: 'number|null',
    source: 'video_metadata',
  }),
  pose2DLandmark: Object.freeze({
    x: 'number|null',
    y: 'number|null',
    confidence: 'number',
    visibility: 'number|null',
    source: 'pose_2d',
  }),
  pose2DFrame: Object.freeze({
    frameIndex: 'number',
    timestampMs: 'number',
    poseDetected: 'boolean',
    reliable: 'boolean',
    keypointCount: 'number',
    landmarks: '{ jointName: pose2DLandmark }',
    missingJoints: 'string[]',
    confidence: 'none|low|moderate|high',
    source: 'pose_2d',
  }),
  pose3DLandmark: Object.freeze({
    x: 'number|null',
    y: 'number|null',
    z: 'number|null',
    confidence: 'number',
    measurementType: 'estimated|measured|not_available',
    source: 'monocular_estimate|multi_view_triangulated',
  }),
  pose3DFrame: Object.freeze({
    frameIndex: 'number',
    timestampMs: 'number',
    joints3d: '{ jointName: pose3DLandmark }',
    source: 'monocular_estimate|multi_view_triangulated',
    measurementType: 'estimated|measured|not_available',
    confidence: 'none|low|moderate|high',
    assumptions: 'string[]',
    cameraCount: 'number|null',
    calibrationQuality: 'none|low|moderate|high',
    syncOffsetMs: 'number|null',
  }),
  biomechanicalMetrics: Object.freeze({
    timestampMs: 'number|null',
    timestampRangeMs: '[number, number]|null',
    source: 'biomechanics_engine',
    confidence: 'none|low|moderate|high',
    measurementType: 'estimated|measured|not_available',
    bodyLineAngleDegrees: 'metric|null',
    spineAngleDegrees: 'metric|null',
    headMovement: 'metric|null',
    hipVerticalDisplacement: 'metric|null',
    shoulderAngleDegrees: 'metric|null',
    elbowAngleDegrees: 'metric|null',
    kneeAngleDegrees: 'metric|null',
    strokeRate: 'metric|null',
    tempo: 'metric|null',
    distancePerStrokeEstimate: 'metric|null',
    leftRightSymmetry: 'metric|null',
    strokeSpecific: 'object',
  }),
  forceEstimate: Object.freeze({
    value: 'number|null',
    unit: 'string',
    estimateType: 'hydrodynamic|propulsion|risk_indicator|not_available',
    measurementType: 'estimated|measured|not_available',
    confidence: 'none|low|moderate|high',
    assumptions: 'string[]',
    source: 'hydrodynamics_engine',
    timestampRangeMs: '[number, number]|null',
  }),
  aiCoachingFinding: Object.freeze({
    title: 'string',
    severity: 'low|medium|high|good|info',
    confidence: 'none|low|moderate|high',
    timestampStartSeconds: 'number|null',
    timestampEndSeconds: 'number|null',
    phase: 'string|null',
    evidenceMetrics: 'object',
    forceExplanation: 'string|null',
    correctionCue: 'string|null',
    drill: 'string|null',
    coachReviewRequired: 'boolean',
    source: 'biomechanics_engine|hydrodynamics_engine|coach_review|manual',
  }),
  fullAnalysisPayloadSummary: Object.freeze({
    schemaVersion: 'swim_sight_biomechanics_v1',
    availabilityState: 'availability state',
    videoMetadata: 'videoMetadata',
    poseSummary: 'pose summary',
    biomechanicsSummary: 'biomechanics summary',
    forceSummary: 'force summary',
    phaseWindows: 'strokePhaseWindow[]',
    aiFindings: 'aiCoachingFinding[]',
    coachApproval: 'coachApprovalState',
    artifacts: 'processingArtifactReference[]',
    publicReportSafe: 'boolean',
  }),
});
